import type { Metadata } from 'next'
import Link from 'next/link'
import { PolicyPage, type PolicySection } from '@/components/public/PolicyPage'
import { MERCHANT } from '@/lib/merchant-details'

export const metadata: Metadata = { title: 'Terms & Conditions — LOCAH', description: 'Terms for LOCAH accounts, digital services, website publishing, platform charges and use of the Marketplace.' }

const sections: PolicySection[] = [
  { id: 'about', title: 'About LOCAH', content: <><p>LOCAH is a digital platform operated by {MERCHANT.legalName} in India. It helps businesses create an online presence and use business-management tools. These Terms govern access to LOCAH and purchases of LOCAH’s own software and digital services.</p><p>Businesses listed on LOCAH are independent merchants. A purchase from one of those businesses is a transaction with that business, not a purchase of a LOCAH platform service. The merchant’s own terms, delivery and refund policies may apply.</p></> },
  { id: 'accounts', title: 'Accounts and eligibility', content: <p>Provide accurate registration and contact details, keep your credentials secure, and tell us promptly about unauthorized account access. You are responsible for activity under your account, subject to applicable law. If you act for a business, you must have authority to provide its information and accept these Terms for it.</p> },
  { id: 'business-information', title: 'Business information and publishing', content: <><p>You are responsible for the accuracy and legality of the business details, products, prices, images and claims you submit or approve for publication. You must have the rights needed to use that material and keep it current.</p><p>LOCAH may use AI to help organize information or draft a website. AI output can be inaccurate; review it before publishing. We may reject or remove content that violates these Terms or applicable law.</p></> },
  { id: 'services-and-prices', title: 'Services, prices and taxes', content: <><p>Current public LOCAH service prices and inclusions are described on the <Link href="/pricing">Pricing page</Link>. The final scope, payable amount and any applicable tax are confirmed before a paid service begins. Features not yet enabled for an account are not promised by a plan description.</p><p>LOCAH platform charges are separate from your customers’ purchases and from third-party charges such as a merchant payment gateway, advertising or delivery. We will identify separately chargeable services before asking you to authorize them.</p></> },
  { id: 'renewal', title: 'Renewals and cancellations', content: <><p>Pay As You Go purchases do not automatically renew. LOCAH Monthly may renew at the end of each billing month where recurring billing is enabled. Cancel before the next renewal to stop future charges; your current paid period remains available through its end.</p><p>For cancellation and refund eligibility, read the <Link href="/refunds">Refund & Cancellation Policy</Link>. If self-service controls are unavailable, <Link href="/contact">contact us</Link> to request cancellation.</p></> },
  { id: 'acceptable-use', title: 'Acceptable use', content: <p>Do not use LOCAH for unlawful, fraudulent, misleading, infringing or abusive activity; attempt to access another account; interfere with service security; or use automated access in a way that harms the platform. We may restrict access while investigating misuse, with notice where appropriate.</p> },
  { id: 'ownership', title: 'Content and intellectual property', content: <p>You retain your rights in material you provide. You grant LOCAH the permission needed to host, process, display and publish that material to provide the service you request. LOCAH’s software, design and trademarks remain ours or our licensors’. Do not copy or resell the platform without permission.</p> },
  { id: 'availability', title: 'Availability and third parties', content: <p>We work to make the service reliable but cannot guarantee uninterrupted access or that AI output or third-party integrations will always be correct or available. External providers may have their own terms. We may change or discontinue features, taking reasonable steps to inform affected customers where practical.</p> },
  { id: 'liability', title: 'Responsibility and applicable law', content: <p>Nothing in these Terms excludes rights or remedies that cannot lawfully be excluded. To the extent permitted by law, LOCAH is not responsible for an independent merchant’s goods, services, fulfilment or claims, or for losses caused by information you supplied inaccurately or published without review. These Terms are governed by the laws of India, with disputes subject to the courts of Chennai, Tamil Nadu, except where applicable law requires otherwise.</p> },
  { id: 'changes-and-contact', title: 'Changes and contact', content: <p>We may update these Terms and will show the revised date on this page. Material changes affecting paid services will be communicated where practical. Questions can be sent to <a href={`mailto:${MERCHANT.email}`}>{MERCHANT.email}</a>; our full details are on the <Link href="/contact">Contact page</Link>.</p> },
]

export default function TermsPage() {
  return <PolicyPage eyebrow="The agreement" title="Terms & Conditions" intro="The rules for using LOCAH and purchasing our digital services, in straightforward language." sections={sections} current="/terms" />
}
