import type { Metadata } from 'next'
import Link from 'next/link'
import { PolicyPage, type PolicySection } from '@/components/public/PolicyPage'
import { MERCHANT } from '@/lib/merchant-details'

export const metadata: Metadata = { title: 'Privacy Policy — LOCAH', description: 'How LOCAH collects, uses, shares and protects account, business and customer data.' }

const sections: PolicySection[] = [
  { id: 'who-we-are', title: 'Who is responsible', content: <p>LOCAH is operated by {MERCHANT.legalName}. This policy describes how we handle personal information when you visit our website, create an account, use our business tools or interact with a business through LOCAH. For a business’s own customer records, that business may also make independent decisions about its data and should explain those practices in its own notice.</p> },
  { id: 'information', title: 'Information we collect', content: <><p>We may collect your name, email, phone number, account credentials, business details, location and website content you provide; messages, bookings, orders and related information you enter or generate in the service; support communications; payment references and billing status; and technical data such as device, browser, IP address and usage events.</p><p>Payment providers process payment credentials under their own notices. Do not send full card details or passwords to LOCAH support.</p></> },
  { id: 'use', title: 'How we use information', content: <p>We use information to create and secure accounts, operate business and Marketplace features, build and host websites, process or reconcile platform purchases, provide support, prevent abuse, improve reliability, communicate service information and meet legal obligations. We may use business-provided material to generate drafts or respond within an AI-assisted workflow requested by the user.</p> },
  { id: 'ai', title: 'AI and connected providers', content: <p>When you use an AI-assisted feature, relevant prompts, business facts, website content or conversation excerpts may be sent to an AI provider to produce the requested result. Other providers may help with hosting, authentication, analytics, communications and payments. Their access should be limited to what is needed for the service they provide. Review generated content before publishing; avoid entering sensitive information that is not needed for the task.</p> },
  { id: 'sharing', title: 'When information is shared', content: <p>We share information with service providers and connected tools needed to operate LOCAH, with the relevant business or customer when you initiate an interaction, with authorities when legally required, and where necessary to protect the service or its users. Public business information and published website content are visible to visitors. We do not describe private account data as publicly available merely because a business has a listing.</p> },
  { id: 'retention', title: 'Retention and security', content: <p>We retain information while needed to provide the service, comply with legal or accounting obligations, resolve disputes and protect against misuse. Retention depends on the category of data and purpose. We use reasonable technical and organizational safeguards, but no online service can guarantee absolute security.</p> },
  { id: 'choices', title: 'Your choices and requests', content: <p>You can request access to, correction of or deletion of your personal information, subject to applicable law and necessary record-keeping. You can also ask about a concern or withdraw consent where the processing is based on consent. Send requests to <a href={`mailto:${MERCHANT.email}`}>{MERCHANT.email}</a> from the contact details associated with your account so we can verify the request.</p> },
  { id: 'cookies', title: 'Cookies and local storage', content: <p>LOCAH may use cookies or similar browser storage to keep you signed in, remember preferences, protect accounts and understand service use. Your browser may let you remove or block them, though essential features may then stop working.</p> },
  { id: 'children-changes', title: 'Children, changes and contact', content: <p>LOCAH business accounts are not intended for children. We may update this policy and will show the revised date here. For privacy questions, contact us using the details on the <Link href="/contact">Contact page</Link>.</p> },
]

export default function PrivacyPage() {
  return <PolicyPage eyebrow="Your information" title="Privacy Policy" intro="What information LOCAH handles, why it is used and how to reach us about it." sections={sections} current="/privacy" />
}
