"""Sector playbook families (Capability Universe §21) — GENERATED, do not edit.

Regenerate with `uv run python tools/codegen/families.py`. Each family
configures modules built once in §6; `core` modules are on by default and
`rec` modules are pre-ticked (owner can untick). Hints in parentheses are
the configuration the source names (e.g. inventory (yield)).
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class Family:
    key: str
    group: str
    label: str
    runs: str
    core: str
    rec: str
    people: str
    ai: str


FAMILIES: tuple[Family, ...] = (
    Family('meat_chicken_fish_shops', '21.1', 'Meat, chicken, fish shops',
           'Orders by weight and cut on WhatsApp and website; live stock of cuts; delivery with tracking; next-morning supplier order',
           'offerings (weighed), orders, payments, inventory (yield), pos, fulfilment, dispatch',
           'messaging, ledger, procurement, trade-network',
           'Cashier, cutting counter screen, delivery partner', 'WhatsApp Manager, Procurement Planner'),
    Family('grocery_kirana_supermarket', '21.1', 'Grocery, kirana, supermarket',
           'Barcode counter billing, khata, "send your list" WhatsApp orders picked and delivered, repeat baskets',
           'pos, invoicing, inventory (batches, expiry), ledger, orders, payments',
           'fulfilment, dispatch, loyalty, procurement, connectors',
           'Cashier, picker, delivery', 'WhatsApp Manager (turns a typed or photographed list into a cart to confirm), Inventory Manager'),
    Family('fruit_vegetable_dairy_egg', '21.1', 'Fruit, vegetable, dairy, egg sellers',
           'Daily subscriptions (e.g. 500 ml milk daily), morning route runs, skip / pause by WhatsApp, month-end bill',
           'memberships (`recurring_delivery`), orders, dispatch, ledger, payments',
           'pos, inventory (perishable), procurement',
           'Route delivery partner', 'Collections Assistant'),
    Family('home_kitchens_pickles_podi', '21.1', 'Home kitchens, pickles, podi, snacks, sweets, home bakers, chocolates',
           'Catalogue with pre-order dates, batch cooking list, city delivery and pan-India shipping for shelf-stable items',
           'offerings, orders, payments, fulfilment',
           'recipes, inventory (batches), invoicing, marketing, reviews',
           'Often solo owner, delivery', 'WhatsApp Manager, Marketing Manager'),
    Family('tiffin_services_meal_subscriptions', '21.1', 'Tiffin services, meal subscriptions, cloud kitchens',
           'Weekly menu calendar, veg / non-veg choice, daily count = subscribers − skips, delivery runs; one kitchen, several brand menus',
           'memberships (`recurring_delivery`), orders, kitchen, dispatch, recipes',
           'procurement, inventory, reviews',
           'Kitchen, delivery', "Procurement Planner (tomorrow's ingredient list), Collections Assistant"),
    Family('restaurants_caf_s_qsr', '21.1', 'Restaurants, cafés, QSR, pubs',
           'QR dine-in ordering, table bookings, kitchen tickets by station, POS with split bills, takeaway and delivery, recipe-based stock, supplier POs',
           'offerings (menu + modifiers), orders, pos, kitchen, payments, invoicing, bookings (table)',
           'recipes, inventory, procurement, trade-network, dispatch, loyalty, reviews, marketing',
           'Cashier, waiter (crew app), kitchen, manager, delivery', 'WhatsApp Manager, Receptionist, Procurement Planner, Review Responder'),
    Family('bakeries_sweet_shops', '21.1', 'Bakeries, sweet shops',
           'Counter POS plus custom cake pre-orders (flavour, weight, message, photo, date), festival pre-order windows, daily production list',
           'pos, orders (dated pre-orders), offerings (weighed + custom), payments (advance)',
           'recipes, kitchen, dispatch, marketing, loyalty',
           'Cashier, baker, delivery', 'WhatsApp Manager, Marketing Manager'),
    Family('catering_canteens', '21.1', 'Catering, canteens',
           'Enquiry → per-plate menu quote → event booking with guest count → advance → BOM-driven purchase (§16.1) → staff roster; canteens get corporate monthly billing',
           'leads, quotes, bookings (event date), payments (milestones), recipes, procurement',
           'trade-network, workforce, invoicing (B2B), ledger',
           'Sales, kitchen head, event staff', 'Sales Executive, Procurement Planner'),
    Family('clothing_footwear_fashion_retail', '21.2', 'Clothing, footwear, fashion retail',
           'Size × colour variants, barcode POS, online catalogue with size guide, exchanges within a window, India-wide shipping',
           'offerings (variants), pos, inventory, orders, payments, fulfilment, invoicing',
           'loyalty, marketing, reviews, connectors',
           'Cashier, store keeper', 'WhatsApp Manager, Marketing Manager'),
    Family('electronics_mobile_stores', '21.2', 'Electronics, mobile stores',
           'Serial / IMEI captured at sale, warranty lookup, installation and repair bookings linked to the sale',
           'offerings (serialised), pos, inventory (serials), invoicing, payments',
           'jobs, bookings, leads',
           'Cashier, technician', 'Receptionist'),
    Family('jewellery', '21.2', 'Jewellery',
           "Price = today's metal rate × weight + making charge + GST from a daily rate board; custom orders with advance; hallmark (HUID) per piece",
           'offerings (formula-priced), pos, invoicing, inventory (per piece), orders',
           'leads, bookings (consultation)',
           'Sales staff, owner', 'Sales Executive'),
    Family('furniture_home_decor_kitchenware', '21.2', 'Furniture, home decor, kitchenware',
           'Dimensions and finishes, made-to-order lead times, showroom visits, delivery + installation slots, bulk quotes',
           'offerings, orders, quotes, payments (advance), fulfilment, dispatch',
           'bookings, jobs (installation), procurement',
           'Sales, delivery / installation crew', 'Sales Executive, Delivery Coordinator'),
    Family('hardware_sports_stationery_books', '21.2', 'Hardware, sports, stationery, books, toys, gifts',
           'High-SKU barcode POS, contractor and school accounts on credit, bulk quotes, seasonal kits (school book lists)',
           'pos, inventory, invoicing, ledger, orders',
           'quotes, loyalty, procurement, connectors',
           'Cashier, store keeper', 'Inventory Manager'),
    Family('cosmetics_optical', '21.2', 'Cosmetics, optical',
           'Cosmetics: batches, expiry, testers. Optical: eye-test slots, frame + lens order sent to the lab, "ready for pickup" message',
           'pos, inventory (batches), orders, invoicing',
           'jobs (lens orders), bookings, loyalty',
           'Cashier, optometrist', 'WhatsApp Manager'),
    Family('tailors_bridal_wear_designer', '21.2', 'Tailors, bridal wear, designer labels',
           'Measurement profile per customer; order stages cutting → stitching → trial → alteration → ready; fitting appointments; delivery-date reminders',
           'orders (stages), customer-relationships (measurements), bookings (fittings), payments (advance)',
           'marketing, reviews',
           'Tailors update stages in the crew app', 'WhatsApp Manager answers status'),
    Family('uniform_suppliers_custom_t', '21.2', 'Uniform suppliers, custom T-shirts, embroidery',
           'B2B quotes with size breakdown per school or company, artwork approval, production stages, bulk delivery, credit terms',
           'quotes, orders, invoicing (B2B), ledger',
           'procurement, recipes (materials per garment), documents (approvals), trade-network',
           'Sales, production', 'Sales Executive, Procurement Planner'),
    Family('leather_goods_bags_handmade', '21.2', 'Leather goods, bags, handmade crafts',
           'Maker catalogue, made-to-order, shipping, wholesale enquiries',
           'offerings, orders, payments, fulfilment',
           'marketing, reviews, quotes (wholesale), recipes (materials)',
           'Solo owner', 'Marketing Manager'),
    Family('salons_barbers_nail_studios', '21.3', 'Salons, barbers, nail studios',
           'Per-stylist calendars, walk-in tokens, service packages, retail products at the counter, deposits for no-show-prone slots',
           'offerings (services), bookings, workforce, queue, payments, pos',
           'memberships (packages), loyalty, reviews, marketing, inventory',
           'Front desk, stylists (own schedule)', 'Receptionist, Appointment Manager, Review Responder'),
    Family('spas_massage_centres_skincare', '21.3', 'Spas, massage centres, skincare clinics',
           'Therapist + room booked together, intake forms with consent, packages, gift vouchers',
           'bookings (provider + room), workforce, payments, documents',
           'memberships, loyalty (gift balance), marketing',
           'Front desk, therapists', 'Receptionist'),
    Family('makeup_artists_bridal_makeup', '21.3', 'Makeup artists, bridal makeup, tattoo and piercing studios',
           'Date bookings with deposit, travel to venue, portfolio, consent forms with an 18+ or guardian check, aftercare messages',
           'bookings, payments (deposit), documents (consent), offerings (portfolio)',
           'quotes (bridal packages), reviews, marketing',
           'Solo or small team', 'Sales Executive'),
    Family('beauty_academies', '21.3', 'Beauty academies',
           'Education pack (§20) plus a student salon floor',
           'academics, memberships (fees), bookings',
           '',
           'Trainers', 'Collections Assistant'),
    Family('gyms_crossfit_powerlifting', '21.3', 'Gyms, CrossFit, powerlifting',
           'Memberships with the renewal ladder (§10), QR check-in, PT session packs, class capacity, freezes',
           'memberships, attendance, payments, bookings',
           'workforce, pos (supplements, merch), marketing, reviews',
           'Front desk, trainers', 'Collections Assistant, Receptionist (trials)'),
    Family('yoga_pilates_dance_fitness', '21.3', 'Yoga, Pilates, dance fitness, martial arts, meditation',
           'Class timetable, drop-ins, class packs, monthly unlimited, waitlists, online links; belt / grade tracking for martial arts',
           'bookings (class), memberships, payments',
           'attendance, academics (grades), marketing',
           'Instructors', 'Appointment Manager'),
    Family('personal_trainers_nutrition_coaches', '21.3', 'Personal trainers, nutrition coaches',
           '1:1 sessions, packages, check-in forms, plans shared as documents',
           'bookings, memberships (session packs), payments',
           'documents, messaging',
           'Solo', 'Appointment Manager'),
    Family('pet_shops_pet_food', '21.3', 'Pet shops, pet food',
           'Commerce pack plus recurring pet-food delivery',
           'pos, inventory, orders, payments',
           'memberships (`recurring_delivery`), dispatch',
           'Cashier, delivery', 'WhatsApp Manager'),
    Family('grooming_boarding_training_dog', '21.3', 'Grooming, boarding, training, dog walking',
           'Pet profiles (breed, vaccination dates), grooming slots, boarding date ranges with daily photo updates, pickup / drop, walkers as field crew',
           'bookings (appointment, stay), customer-relationships (pet profiles), payments',
           'dispatch, tasks (feeding, cleaning), memberships (walk packs)',
           'Groomers, walkers (crew app)', 'Receptionist'),
    Family('veterinary_clinics', '21.3', 'Veterinary clinics',
           'Health front desk with the pet as the patient: appointments, token queue, vaccination-due reminders, pharmacy counter, wellness plans',
           'bookings, queue, workforce, pos, memberships (wellness plans)',
           'messaging',
           'Reception, vets', 'Receptionist'),
    Family('hospitals_polyclinics', '21.4', 'Hospitals, polyclinics',
           'Departments, doctor schedules, OPD appointments with tokens, live queue board, walk-ins, consultation billing, reminders',
           'bookings (provider / department), queue, workforce, payments, invoicing',
           'documents (registration forms), messaging, reviews',
           'Reception, doctors (own OPD list), billing desk', 'Receptionist, Appointment Manager'),
    Family('clinics_dental_eye_ent', '21.4', 'Clinics: dental, eye, ENT, dermatology, paediatrics, fertility, physiotherapy',
           'Same front desk plus treatment plans in instalments, physio session packs, recall reminders (e.g. 6-month dental check), consent forms',
           'bookings, queue, payments, memberships (session packs, plans)',
           'documents, reviews',
           'Reception, provider', 'Receptionist'),
    Family('diagnostic_centres_medical_labs', '21.4', 'Diagnostic centres, medical labs',
           'Test catalogue with preparation notes, slot booking, home sample collection as dispatch jobs, report-ready message with a secure expiring link, corporate packages',
           'offerings (tests), bookings, dispatch, documents (reports), payments',
           'invoicing (B2B), marketing',
           'Front desk, phlebotomists (crew app), lab', 'Receptionist'),
    Family('pharmacies', '21.4', 'Pharmacies',
           'Batch / expiry POS, prescription upload for Rx items verified by the pharmacist, refill reminders (with consent), local delivery, distributor POs',
           'pos, inventory (batches), orders, invoicing, payments',
           'dispatch, procurement, trade-network, memberships (refills)',
           'Pharmacist, delivery', 'WhatsApp Manager (non-medical only), Inventory Manager'),
    Family('home_nursing_caregivers_ambulance', '21.4', 'Home nursing, caregivers, ambulance services',
           'Caregivers as field crew with rosters, visit check-in / out, monthly care contracts, family updates; ambulance requests captured with location (never a substitute for 108 / 112)',
           'workforce, dispatch, memberships (`service_contract`), attendance',
           'documents, tasks',
           'Caregivers, coordinator', 'Delivery Coordinator'),
    Family('elder_care_assisted_living', '21.4', 'Elder care, assisted living',
           'Long-stay rooms, monthly fees, activity schedules, family announcements',
           'bookings (long stay), memberships, tasks',
           'documents, messaging',
           'Care staff', 'Collections Assistant'),
    Family('therapy_psychologists_counsellors_speech', '21.4', 'Therapy: psychologists, counsellors, speech, occupational, rehab',
           'Private mode: minimal data, online session links, session packs, discreet reminders ("Reminder: your 5 pm appointment"), reviews off by default',
           'bookings, memberships (session packs), payments',
           'documents (intake, consent)',
           'Therapist, front desk', 'Appointment Manager'),
    Family('daycare_play_schools_activity', '21.4', "Daycare, play schools, activity centres, kids' sports",
           'Fee plans, attendance with an authorised pick-up list, daily notes, activity batches, trial classes',
           'memberships (`fee_plan`), attendance, academics, payments',
           'documents, messaging',
           'Teachers, coaches', 'Collections Assistant'),
    Family('maternity_services', '21.4', 'Maternity services',
           'Classes and consultations with packages',
           'bookings, memberships (packs), payments',
           '',
           'Provider', 'Receptionist'),
    Family('testing_calibration_r_d', '21.4', 'Testing, calibration, R&D, inspection labs',
           'Sample intake → test job → results → certificate PDF with a QR verification link; client accounts on credit; accreditation number shown',
           'quotes, jobs, documents (certificates), invoicing (B2B), ledger',
           'dispatch (sample pickup), bookings (inspection visits)',
           'Lab staff, inspectors', 'Sales Executive'),
    Family('coaching_institutes_tuition_centres', '21.5', 'Coaching institutes (NEET / JEE), tuition centres',
           'Admissions pipeline, batches, test series, marks, batch transfers, fee instalments, guardian portal',
           'academics, attendance, memberships (`fee_plan`), payments, leads',
           'documents, messaging, marketing',
           'Counsellors, teachers, office', 'Receptionist (admissions), Collections Assistant, Sales Executive'),
    Family('schools_preschools', '21.5', 'Schools, preschools',
           'Admissions enquiries, fee collection, announcements, attendance; a full school ERP is FUTURE',
           'leads, memberships (fees), academics (light), messaging',
           'documents',
           'Office, teachers', 'Receptionist, Collections Assistant'),
    Family('language_music_dance_coding', '21.5', 'Language, music, dance, coding academies',
           'Levels and grades, session packs, recitals, hybrid online / offline batches',
           'academics, bookings (class), memberships, payments',
           'attendance, marketing',
           'Instructors', 'Appointment Manager'),
    Family('vocational_institutes_driving_schools', '21.5', 'Vocational institutes, driving schools',
           'Batches, practical hours, certificates; driving: instructor + vehicle slots, learner and test dates',
           'academics, bookings (vehicle + instructor), memberships (fees)',
           'documents, dispatch (pickup for lessons)',
           'Instructors (crew app)', 'Appointment Manager'),
    Family('individual_tutors', '21.5', 'Individual tutors (maths, science, German, IELTS, music, art)',
           'One-person calendar, session packs, UPI links, homework sharing, parent updates, profile page',
           'bookings, memberships (session packs), payments',
           'academics (light), messaging',
           'Solo', 'Appointment Manager'),
    Family('online_educators_course_sellers', '21.5', 'Online educators, course sellers',
           'Digital products and cohorts as batches; recorded content stays on an external host (LMS FUTURE)',
           'offerings (digital), orders, payments, memberships',
           'marketing, academics (cohorts)',
           'Solo or small team', 'Marketing Manager'),
    Family('youtubers_influencers_podcasters_newsletter', '21.5', 'YouTubers, influencers, podcasters, newsletter creators',
           'Link-in-bio storefront, merch, brand-deal enquiries with a rate-card quote, paid 1:1 calls, community memberships',
           'website, leads, quotes, bookings (1:1), payments',
           'offerings (merch, digital), memberships, invoicing',
           'Creator, manager', 'Sales Executive'),
    Family('coaches_speakers_authors', '21.5', 'Coaches, speakers, authors',
           'Speaking enquiries → quote + event date, book sales, workshops as capacity-limited bookings',
           'leads, quotes, bookings, payments',
           'offerings, marketing',
           'Solo', 'Sales Executive'),
    Family('hotels_resorts', '21.6', 'Hotels, resorts',
           'Room types and named rooms, date-range availability, deposits, check-in with guest ID capture, housekeeping board, restaurant charges posted to the room, direct booking engine',
           'bookings (stay), offerings (room types), payments (deposit), tasks (housekeeping), invoicing',
           'pos (charge to room), documents (guest ID), reviews, marketing',
           'Front desk, housekeeping (crew app), manager', 'Receptionist, Review Responder'),
    Family('homestays_hostels_villa_rentals', '21.6', 'Homestays, hostels, villa rentals',
           'Per-room or per-bed dates, self check-in instructions by WhatsApp, cleaning task between stays',
           'bookings (stay), payments, tasks',
           'documents, reviews',
           'Owner, cleaner', 'Receptionist'),
    Family('travel_agencies_tour_operators', '21.6', 'Travel agencies, tour operators, pilgrimage tours, guides',
           'Packages with departure dates and seats, custom itinerary quotes, traveller documents, payment milestones, itinerary PDF, on-trip WhatsApp support',
           'offerings (packages), quotes, bookings (departures), payments (milestones), documents',
           'leads, marketing, reviews',
           'Sales, trip coordinator', 'Sales Executive'),
    Family('adventure_tourism', '21.6', 'Adventure tourism',
           'Capacity-limited slots, signed waivers, gear rental, weather cancellations with refunds',
           'bookings, documents (waivers), payments',
           'rentals, reviews',
           'Guides (crew app)', 'Receptionist'),
    Family('event_wedding_planners_decorators', '21.6', 'Event and wedding planners, decorators',
           'Enquiry → consultation → package quote → contract → payment milestones → event project with checklist and vendor POs → day-of run sheet',
           'leads, quotes, projects, payments, tasks',
           'procurement (vendors), trade-network, documents',
           'Planner, coordinators', 'Sales Executive'),
    Family('mandapams_banquet_community_halls', '21.6', 'Mandapams, banquet and community halls',
           'Date calendar (auspicious dates in demand), hall + add-ons, advance and balance, cancellation rules, utility charges after the event',
           'bookings (event date), quotes, payments (advance), documents',
           'tasks, reviews',
           'Manager', 'Receptionist'),
    Family('florists_djs_sound_light', '21.6', 'Florists, DJs, sound and light rental, invitation printers',
           'Event-date orders, equipment inventory by date, delivery and setup crew',
           'bookings, orders, dispatch',
           'quotes, tasks',
           'Setup crew (crew app)', 'Delivery Coordinator'),
    Family('rentals_cars_bikes_cameras', '21.6', 'Rentals: cars, bikes, cameras, tools, equipment, party gear, furniture, costumes, dresses',
           'Availability calendar per item, deposit hold, ID / licence check, photo handover checklist, return inspection, damage and late fees, delivery / pickup',
           'offerings (`rental_resource`), bookings (rental), payments (deposit), documents, tasks',
           'dispatch, jobs (maintenance), reviews',
           'Counter staff, delivery', 'Receptionist'),
    Family('co_working_office_rental', '21.6', 'Co-working, office rental, meeting rooms, incubators',
           'Hot / dedicated desk memberships, meeting-room booking with credits, visitor passes, monthly B2B invoices',
           'memberships (access), bookings (rooms), invoicing (B2B), payments',
           'attendance, ledger',
           'Community manager', 'Receptionist'),
    Family('warehousing_cold_storage_self', '21.6', 'Warehousing, cold storage, self-storage, document storage',
           'Space units (pallets, lockers), storage contracts, inward / outward log per client, billing by space and handling, client stock view',
           'memberships (`service_contract`), inventory (client-owned stock), invoicing (B2B), ledger',
           'dispatch, documents',
           'Warehouse staff', 'Bookkeeper'),
    Family('developers_builders_plot_sellers', '21.7', 'Developers, builders, plot sellers',
           '§19 in full, plus construction progress updates, possession checklist and post-possession maintenance tickets',
           'offerings (projects, units), leads, quotes, bookings (site visits), projects, payments (schedule), documents',
           'marketing, procurement, trade-network',
           'Sales, channel partners, site engineer', 'Sales Executive, Receptionist'),
    Family('brokers_agencies_rental_agencies', '21.7', 'Brokers, agencies, rental agencies, commercial real estate',
           'Listings sourced with owner consent, buyer requirements matched to listings, site visits, rental agreements, brokerage invoices',
           'offerings (listings), leads, bookings (site visits), documents',
           'memberships (rent), invoicing, marketing',
           'Brokers (crew app)', 'Sales Executive'),
    Family('property_management_co_living', '21.7', 'Property management, co-living',
           'Tenants, monthly rent + maintenance, deposits, maintenance requests as jobs, move-in / move-out checklists',
           'memberships (rent), bookings (long stay), jobs, payments, ledger',
           'documents, tasks',
           'Manager, maintenance staff', 'Collections Assistant'),
    Family('architects_interior_designers_landscape', '21.7', 'Architects, interior designers, landscape architects',
           'Portfolio, consultation booking, fee proposal, stages (concept → design → execution) with client approval of each drawing, BOQ quotes, site logs, milestone billing, vendor POs',
           'offerings (portfolio), leads, quotes (BOQ), projects, documents (approvals), payments',
           'procurement, trade-network, tasks',
           'Designers, site supervisor (crew app)', 'Sales Executive'),
    Family('modular_kitchens_renovation_furniture', '21.7', 'Modular kitchens, renovation, furniture designers',
           'Measurement visit → design → quote → production → installation job → warranty',
           'bookings (measurement), quotes, projects, jobs (installation), payments',
           'procurement, recipes (BOM per module), dispatch',
           'Measurers, installers (crew app)', 'Sales Executive'),
    Family('contractors_civil_electrical_plumbing', '21.7', 'Contractors: civil, electrical, plumbing, painting, roofing, flooring, fabrication, waterproofing, HVAC',
           'BOQ estimates, work orders, daily labour attendance on site, material requisitions from site to supplier, progress photos, running-account bills, retention money, subcontractors',
           'quotes, projects, workforce (site attendance), procurement, invoicing (B2B), ledger',
           'jobs (small works), documents, trade-network',
           'Site supervisor (crew app), labour', 'Procurement Planner'),
    Family('solar_epc_ev_charging', '21.7', 'Solar EPC, EV charging, battery storage, generator rental',
           'Site survey booking, load assessment form, system quote with owner-entered subsidy details, installation project, net-metering paperwork checklist, AMC',
           'leads, bookings (survey), quotes, projects, documents, memberships (AMC)',
           'jobs (service), marketing',
           'Surveyors, installers', 'Sales Executive'),
    Family('waste_management_recycling_composting', '21.7', 'Waste management, recycling, composting, water treatment, environmental consultancy',
           'Recurring pickup routes, weight log per pickup, service contracts with housing societies and businesses, compliance certificates',
           'memberships (`service_contract`), dispatch (recurring), documents, invoicing',
           'quotes, jobs',
           'Collection crew', 'Delivery Coordinator'),
    Family('home_services_cleaning_pest', '21.8', 'Home services: cleaning, pest control, plumbing, electrical, appliance / AC / RO service, gardening',
           'Booking with address and a photo of the problem, technician dispatch, job card (inspect → estimate → customer approves on WhatsApp → work → parts → pay), AMC visits, seasonal reminders (AC service before summer)',
           'bookings, jobs, dispatch, payments, memberships (AMC)',
           'inventory (van stock), quotes, reviews, marketing',
           'Dispatcher, technicians (crew app)', 'Receptionist, Appointment Manager'),
    Family('laundry_dry_cleaning', '21.8', 'Laundry, dry cleaning',
           'Pickup / drop slots, a barcode tag per garment, per-item or per-kg pricing, processing stages, ready alert, laundry plans',
           'orders (stages), dispatch, pos, payments',
           'memberships, ledger',
           'Counter, riders', 'WhatsApp Manager'),
    Family('repair_specialists_it_support', '21.8', 'Repair specialists (watch, shoe, jewellery, furniture, electronics, machinery) and IT support (computer, mobile, printer, CCTV, networking)',
           "Intake with photos against the customer's asset, job stages, estimate approval, parts, repair warranty, ready alert; CCTV and networking as install projects + AMC",
           'jobs, customer-relationships (assets), payments, invoicing',
           'inventory (parts), quotes, memberships (AMC), dispatch',
           'Technicians', 'Receptionist'),
    Family('car_bike_dealers_used', '21.8', 'Car and bike dealers, used cars',
           'Vehicle inventory with photos and specs, test-drive bookings, finance enquiry passed to a partner, on-road price quote, RC-transfer checklist, delivery checklist',
           'offerings (vehicles), leads, bookings (test drive), quotes, documents',
           'marketing, invoicing, jobs (service)',
           'Sales executives', 'Sales Executive, Receptionist'),
    Family('garages_mechanics_car_wash', '21.8', 'Garages, mechanics, car wash, detailing, tyres, batteries, spare parts',
           'Vehicle profile (registration, model, odometer), service booking, job card with inspection photos, WhatsApp estimate approval, parts from stock, ready alert, reminders by date or km, wash plans; parts sold to garages on credit',
           'jobs, customer-relationships (vehicles), bookings, inventory (parts), invoicing, payments',
           'memberships, procurement, ledger, reviews',
           'Service advisor, mechanics (crew app)', 'Receptionist, Collections Assistant'),
    Family('car_rental_driver_services', '21.8', 'Car rental, driver services',
           'Rental calendar (§21.6) plus drivers as crew for trip bookings',
           'bookings, dispatch, payments, documents',
           'expenses',
           'Drivers (crew app)', 'Receptionist'),
    Family('courier_packers_movers_trucking', '21.8', 'Courier, packers and movers, trucking, freight, fleet operators',
           'Survey-based quotes for moves, shipment bookings, milestone tracking, consignment notes, proof of delivery, fleet and driver assignment, fuel and toll expenses, B2B invoices',
           'quotes, orders (shipments), dispatch, documents, invoicing, ledger',
           'expenses, workforce, trade-network',
           'Dispatcher, drivers (crew app)', 'Delivery Coordinator'),
    Family('taxi_bus_operators_last', '21.8', 'Taxi, bus operators, last-mile delivery companies',
           'Trip and seat bookings; for delivery firms, client jobs in by CSV / API, riders on the crew app, COD remitted to clients, per-drop billing',
           'bookings (seats, trips), dispatch, ledger, invoicing',
           'connectors, expenses',
           'Drivers, riders', 'Delivery Coordinator'),
    Family('security_agencies_alarm_fire', '21.8', 'Security agencies, alarm and fire-safety firms',
           'Client contracts, guard rosters per site, geo-verified attendance, incident reports, monthly billing per post; installs + AMC + inspection certificates',
           'memberships (`service_contract`), workforce, attendance, invoicing (B2B), documents',
           'jobs, payroll FUTURE',
           'Supervisors, guards (crew app)', 'Collections Assistant'),
    Family('facilities_management_commercial_cleaning', '21.8', 'Facilities management, commercial cleaning, maintenance, manpower supply',
           'Site contracts, rosters, attendance, site checklists with photo proof, consumables stock per site',
           'memberships, workforce, attendance, tasks, invoicing',
           'inventory (per-site consumables), jobs',
           'Supervisors, staff (crew app)', '—'),
    Family('recruitment_temp_staffing_domestic', '21.8', 'Recruitment, temp staffing, domestic-help agencies',
           'Candidate and client pipelines, openings as projects, placements, verification documents, replacement guarantee period, fee invoices',
           'leads, projects, documents, invoicing',
           'memberships (guarantee period), workforce (temp deployment)',
           'Recruiters', 'Sales Executive'),
    Family('chartered_accountants_accountants_tax', '21.9', 'Chartered accountants, accountants, tax consultants, company secretaries, bookkeeping',
           'Client onboarding, monthly retainers, per-client compliance calendar (GST, income tax, company filings) turned into tasks, WhatsApp document requests with an upload link, invoices and receivables',
           'memberships (retainers), tasks, documents, invoicing, ledger, compliance',
           'bookings, leads',
           'Partners, staff', 'Bookkeeper (document chase), Collections Assistant'),
    Family('lawyers', '21.9', 'Lawyers',
           'Consultations, matters as projects with hearing dates, documents, fee notes, retainers; strict access per matter',
           'bookings, projects (matters), documents, invoicing',
           'memberships (retainers), leads',
           'Advocates, clerks', 'Receptionist'),
    Family('management_hr_business_b2b', '21.9', 'Management, HR, business and B2B consultants (process, engineering, ISO, supply chain)',
           'Proposals, engagements with milestones, retainers, milestone invoicing',
           'leads, quotes, projects, invoicing, ledger',
           'bookings, documents',
           'Consultants', 'Sales Executive'),
    Family('financial_advisers_insurance_agents', '21.9', 'Financial advisers, insurance agents, loan consultants, mortgage brokers, wealth managers',
           'Client book, policy and loan renewal dates as customer assets, lead pipeline, document collection, renewal reminders',
           'leads, customer-relationships (policy assets), documents, bookings',
           'memberships (advisory fees), marketing (restricted)',
           'Advisers', 'Sales Executive, Collections Assistant (reminders only)'),
    Family('software_saas_it_services', '21.9', 'Software, SaaS, IT services, web / app development, cybersecurity, cloud, data and AI consultancies',
           'Proposals, milestone projects, retainers and AMCs, support tickets, domestic and export invoices',
           'leads, quotes, projects, memberships (retainers), invoicing',
           'jobs (tickets), documents',
           'Delivery team', 'Sales Executive'),
    Family('photographers_videographers_filmmakers_editors', '21.9', 'Photographers, videographers, filmmakers, editors, drone operators',
           'Portfolio, date availability, package quotes, deposit, shoot booking, delivery milestones (album, film), gallery link delivered on the project, second-shooter crew',
           'offerings (portfolio, packages), bookings (event date), quotes, payments, projects',
           'documents (contracts), reviews',
           'Crew (crew app)', 'Sales Executive'),
    Family('ad_digital_marketing_seo', '21.9', 'Ad, digital marketing, SEO, social media, branding, PR, content studios, influencer management',
           'Retainers, deliverables calendar per client, creative approvals with version history, invoices; creator roster and brand deals for influencer managers',
           'memberships (retainers), projects, documents (approvals), invoicing, leads',
           'quotes, tasks',
           'Account managers', 'Sales Executive'),
    Family('graphic_designers_illustrators_artists', '21.9', 'Graphic designers, illustrators, artists, animators, UX and fashion designers, writers, musicians',
           'Portfolio site, commission enquiry → quote → deposit → counted revisions → delivery; print and original sales; gigs and lessons for musicians',
           'offerings (portfolio), leads, quotes, payments, projects (light)',
           'orders (prints), bookings (gigs, lessons)',
           'Solo', 'Sales Executive'),
    Family('industrial_suppliers_pumps_valves', '21.10', 'Industrial suppliers: pumps, valves, motors, bearings, instrumentation, chemicals, lab and safety equipment, panels, automation, machine tools',
           'Technical catalogue with specs and datasheets, industries served, RFQ → quote with MOQ and lead time, customer price lists, credit terms, PO → sales order → dispatch → invoice → receivables, repeat-order portal',
           'offerings (specs, datasheets), quotes (RFQ), orders, invoicing (B2B), ledger',
           'trade-network, dispatch, leads, marketing, connectors',
           'Sales engineers, accounts, dispatch', 'Sales Executive, Bookkeeper'),
    Family('manufacturers_food_textiles_garments', '21.10', 'Manufacturers: food, textiles, garments, plastics, chemicals, pharma, auto components, machinery, furniture, metal fabrication',
           'Orders from distributors, BOM and production batches (material requirement from orders), raw-material purchasing, lot tracking, QC checklists, certificates of analysis, dispatch, job-work challans',
           'recipes (BOM), procurement, inventory (lots), orders, invoicing (B2B), quotes',
           'trade-network, tasks (QC), documents, connectors',
           'Production supervisor, store keeper, QC', 'Procurement Planner, Inventory Manager'),
    Family('oem_engineering_firms_process', '21.10', 'OEM and engineering firms: process equipment, boilers, compressors, water treatment, conveyors, automation',
           'Enquiry → site survey → technical + commercial proposal → PO → project (design, fabrication, install, commissioning) → AMC and spares on an installed-base register',
           'leads, quotes, projects, payments (milestones), jobs (service), memberships (AMC)',
           'procurement, documents, trade-network',
           'Application and service engineers (crew app)', 'Sales Executive'),
    Family('packaging_printing_signage', '21.10', 'Packaging (boxes, labels, bottles, flexible, food packaging) and printing / signage (press, digital, flex, engraving, laser cutting)',
           'Spec-based quotes with quantity breaks, artwork approval, job tickets through production stages, one-tap repeat orders, B2B credit; walk-in print jobs at a counter',
           'quotes, orders (job stages), documents (artwork approvals), invoicing, ledger',
           'recipes (material per job), procurement, pos',
           'Estimators, operators', 'Sales Executive'),
    Family('wholesale_distribution_fmcg_pharma', '21.10', 'Wholesale and distribution: FMCG, pharma, food, electrical, building material, industrial',
           'Retailer ordering on WhatsApp with retailer-specific prices, salesman beat plans with order-taking in the crew app, credit limits and collections, van sales, schemes (buy 10 get 1), delivery runs, expiry and return claims',
           'orders (B2B), price lists, ledger, dispatch, inventory (batches), invoicing',
           'trade-network, pos (van sales), marketing (schemes), connectors',
           'Salesmen (crew app), delivery, accounts', 'WhatsApp Manager (retailer reorders), Collections Assistant, Procurement Planner'),
    Family('import_export_trading_companies', '21.10', 'Import / export, trading companies',
           'Overseas enquiries, proforma invoices in foreign currency, Incoterms, shipment milestones, export documents (packing list, certificate of origin), payment terms',
           'quotes (proforma), orders, documents, invoicing (foreign currency), ledger',
           'trade-network, procurement',
           'Export executive', 'Sales Executive'),
    Family('farms_organic_dairy_poultry', '21.10', 'Farms: organic, dairy, poultry, fish, mushroom, hydroponics, nurseries',
           'Produce-box subscriptions, farm-gate orders, farm visits; harvest availability lists and pre-orders for restaurants and wholesalers; daily output and feed-stock logs; nursery catalogue + landscaping enquiries',
           'offerings, orders, memberships (produce boxes), inventory (harvest lots)',
           'trade-network, quotes (bulk), bookings (visits), dispatch',
           'Farm manager, delivery', 'Procurement Planner (feed, seed)'),
    Family('agri_services_tractor_rental', '21.10', 'Agri services: tractor rental, irrigation, farm consultancy, seed, fertiliser and equipment dealers',
           'Rental with operator by hour or acre, dealer counter with seasonal credit repaid at harvest, consultancy bookings',
           'bookings (rental + operator), pos, ledger (seasonal credit), inventory',
           'dispatch, memberships',
           'Operators (crew app)', 'Collections Assistant'),
    Family('clubs_sports_hobby_clubs', '21.11', 'Clubs, sports and hobby clubs, associations, chambers, member networks',
           'Opt-in member directory, annual dues, facility booking (courts, rooms), events with RSVPs and capacity, committee announcements',
           'memberships (`member_dues`), bookings (facilities, events), messaging, payments',
           'documents, workforce (volunteers)',
           'Secretary, treasurer', 'Collections Assistant'),
    Family('temple_service_organisations_cultural', '21.11', 'Temple service organisations, cultural centres, trusts, community halls',
           'Donations, dated seva / pooja bookings, hall bookings, sponsorships (e.g. annadhanam), festival schedules, receipts',
           'donations, bookings (seva, hall), payments, messaging',
           'memberships, documents',
           'Office staff, volunteers', 'Receptionist'),
    Family('ngos_animal_rescue_education', '21.11', 'NGOs, animal rescue, education NGOs, charities, social enterprises',
           'Causes and campaigns, one-off and recurring donations, 80G receipts, donor timeline and updates, volunteer rosters, donor / CSR reports, product sales for social enterprises',
           'donations, customer-relationships (donors), payments, messaging',
           'workforce (volunteers), documents, marketing, orders',
           'Coordinators, volunteers', 'Collections Assistant, Marketing Manager'),
)

BY_KEY: dict[str, Family] = {f.key: f for f in FAMILIES}
