"""Image generation for Website and Offering media.

Doc 12 §12.6: AI never writes external URLs into content. Generated bytes are
persisted as `media_assets` and only the asset id is stored on sections /
offerings. Failure is non-fatal — the site stays editable without a broken
image URL.

What gets drawn is artwork, never evidence. A generated picture of "our
clinic", "our chef" or "our sofa" would show a visitor something that does not
exist, so every prompt asks for editorial illustration, texture or abstract
atmosphere, and forbids people, storefronts, signage and products presented
as real. The owner's own photos always come first; artwork only fills a gap.

Provider: IMAGE_PROVIDER=gemini (default, GEMINI_IMAGE_MODEL) or xai. There is
no automatic fallback between them — a failed image is a missing image, not a
second paid call.
"""

from __future__ import annotations

import base64
import os
import time
from dataclasses import dataclass
from typing import Any

import httpx

from platform_core.logging import get_logger

_log = get_logger("website.image_generation")

_XAI_IMAGES_URL = "https://api.x.ai/v1/images/generations"
_DEFAULT_IMAGE_MODEL = os.getenv("XAI_IMAGE_MODEL", "grok-imagine-image-2.0")
_GEMINI_BASE = "https://generativelanguage.googleapis.com/v1beta"
GEMINI_IMAGE_MODEL = "gemini-3.1-flash-image"

# A mood and a material for each family — never a scene. The renderer already
# has the business's words; the artwork only has to feel like the trade.
_SCENE_BY_FAMILY: dict[str, str] = {
    "food": "warm spice and ember tones, soft rising curves like steam, hand-made paper grain",
    "appointment": "calm diffused light, soft gradients, gentle rounded geometry, clean air",
    "membership": "strong diagonal forces, high contrast, a sense of motion and effort",
    "stay": "evening window light, linen-like softness, quiet layered planes",
    "retail": "rhythmic stacked forms, warm light across textured surfaces",
    "property": "architectural lines and open space, calm horizons, light and shadow",
    "professional": "precise geometric structure, measured grid lines, engineered rhythm",
    "education": "open layered shapes, a sense of growth and steps, soft chalk-like texture",
    "repair": "strong tool-steel greys, machined curves, practical workshop light",
    "rental": "modular blocks and open space, clean and flexible",
    "furniture": "the rhythm of timber grain, soft light across wood-toned planes, joinery-like lines",
    "general": "warm, specific, layered abstract shapes with a subtle paper texture",
}

# Everything a generated picture must never pretend to show.
_NEVER = (
    "No text, letters or numbers. No logos or signage. No people, faces or hands. "
    "No buildings, shopfronts or interiors presented as a real place. No products, "
    "dishes, equipment or medical imagery presented as real. It must read clearly "
    "as artwork, not as a photograph of a business."
)

_FAMILY_BY_TYPE: dict[str, str] = {
    "restaurant": "food",
    "cafe": "food",
    "food": "food",
    "salon": "appointment",
    "spa": "appointment",
    "clinic": "appointment",
    "gym": "membership",
    "studio": "membership",
    "hotel": "stay",
    "homestay": "stay",
    "retail": "retail",
    "grocery": "retail",
    "real_estate": "property",
    "professional": "professional",
    "agency": "professional",
    "coaching": "education",
    "education": "education",
    "repair": "repair",
    "rental": "rental",
    "furniture": "furniture",
    "manufacturer": "professional",
    "wholesale": "professional",
    "hospital": "appointment",
}


@dataclass(frozen=True)
class GeneratedImage:
    mime_type: str
    bytes: bytes
    model: str
    latency_ms: int
    prompt: str


def family_for_business_type(business_type: str | None) -> str:
    key = (business_type or "other").strip().lower()
    return _FAMILY_BY_TYPE.get(key, "general")


def hero_prompt(
    *,
    display_name: str,
    business_type: str | None,
    description: str | None,
    palette: tuple[str, ...] = (),
) -> str:
    """Wide editorial artwork for a homepage header — atmosphere, not a scene.

    `display_name` and `description` are deliberately not sent: a model given
    "Teakwood Furniture Co makes sofas" draws a sofa and a sign.
    """
    del display_name, description
    family = family_for_business_type(business_type)
    colours = ", ".join(c for c in palette if c) or "a restrained, natural palette"
    return (
        "Wide editorial artwork for the header of a small business website. "
        f"Mood and material: {_SCENE_BY_FAMILY[family]}. Colours: {colours}, with soft neutrals. "
        "Abstract or semi-abstract, textured and layered, with calm open space on the left "
        "where a headline will sit. " + _NEVER
    )


def logo_prompt(*, initial: str, primary: str | None) -> str:
    """A single-letter monogram: the one kind of logo a model draws reliably."""
    letter = (initial or "").strip()[:1].upper() or "A"
    colour = primary or "a deep, confident colour"
    return (
        f"A simple flat vector monogram logo: the single capital letter {letter}, "
        f"in {colour}, set inside a clean geometric shape, centred on a plain white "
        "background with generous padding. Balanced, minimal, timeless. Only that one "
        "letter — no other letters, words, slogans, gradients, mockups, shadows or 3D."
    )


def brand_logo_prompt(
    *, name: str, category: str = "", direction: str = "", palette: tuple[str, ...] = ()
) -> str:
    """A logo from brand context — never from the conversation transcript.

    The business name, what kind of business it is, the feel the owner asked
    for and the site's colours. Nothing the owner said about customers, prices
    or people reaches the image provider.
    """
    colours = ", ".join(c for c in palette if c) or "two harmonious brand colours"
    kind = f", a {category}" if category else ""
    feel = f" The feel: {direction[:160]}." if direction else " Warm, simple and trustworthy."
    return (
        f"Design a clean, modern logo for \"{name[:60]}\"{kind}. A simple flat vector mark with the "
        f"business name set in clear, correctly spelled lettering beside or below it.{feel} Use "
        f"{colours} on a plain white background, centred, with generous padding. No mockups, "
        "no photographs, no extra words, no taglines, no gradients, no 3D."
    )


def offering_prompt(
    *,
    display_name: str,
    business_type: str | None,
    title: str,
    description: str | None,
) -> str:
    # An illustration of the idea, clearly drawn — a photoreal "our dish" would
    # be a picture of food this kitchen never made.
    del display_name, description
    family = family_for_business_type(business_type)
    return (
        f"A flat editorial illustration evoking '{title[:80]}', drawn simply with a few "
        f"shapes. Mood: {_SCENE_BY_FAMILY[family]}. Clearly an illustration, not a photo. "
        "No text, letters, logos, price tags, people or faces."
    )


def image_provider() -> str:
    return (os.getenv("IMAGE_PROVIDER") or "gemini").strip().lower()


def image_generation_available() -> bool:
    """Whether the configured image provider has its key. No key, no button."""
    provider = image_provider()
    if provider == "gemini":
        return bool(os.getenv("GEMINI_API_KEY", "").strip())
    if provider in {"xai", "grok"}:
        return bool(os.getenv("XAI_API_KEY", "").strip())
    return False


def image_model() -> str:
    if image_provider() == "gemini":
        return (os.getenv("GEMINI_IMAGE_MODEL") or GEMINI_IMAGE_MODEL).strip()
    return os.getenv("XAI_IMAGE_MODEL", _DEFAULT_IMAGE_MODEL).strip() or _DEFAULT_IMAGE_MODEL


def gemini_image_body(prompt: str, aspect_ratio: str) -> dict[str, Any]:
    return {
        "contents": [{"role": "user", "parts": [{"text": prompt}]}],
        "generationConfig": {
            "responseModalities": ["IMAGE"],
            "imageConfig": {"aspectRatio": aspect_ratio},
        },
    }


def gemini_image_from(payload: Any) -> tuple[str, bytes] | None:
    """The first inline image in a generateContent response."""
    if not isinstance(payload, dict):
        return None
    for candidate in payload.get("candidates") or []:
        parts = ((candidate or {}).get("content") or {}).get("parts") or []
        for part in parts:
            inline = (part or {}).get("inlineData") or (part or {}).get("inline_data")
            if isinstance(inline, dict) and inline.get("data"):
                mime = str(inline.get("mimeType") or inline.get("mime_type") or "image/png")
                return mime, base64.b64decode(inline["data"])
    return None


# Why an image was not made, in terms an owner-facing message can use. A quota
# or billing refusal must never read like Locah misunderstanding the owner.
FAILURE_REASONS = {
    "unavailable": "Image generation isn't available on this environment right now.",
    "quota": "Image generation has reached its limit for now — try again later, or upload one.",
    "billing": "Image generation isn't enabled for this account yet — upload one, or try again "
               "once it's enabled.",
    "rejected": "The image provider declined this request. You can try again or upload one.",
    "error": "The picture couldn't be made this time. You can try again or upload one.",
}


def _reason_for(status: int, body: str) -> str:
    low = body.lower()
    if status == 429 or "quota" in low or "rate limit" in low:
        return "quota"
    if status in (402, 403) or "billing" in low or "credits" in low:
        return "billing"
    if status == 400:
        return "rejected"
    return "error"


async def _generate_gemini(
    prompt: str, *, aspect_ratio: str, timeout_seconds: int
) -> tuple[GeneratedImage | None, str]:
    api_key = os.getenv("GEMINI_API_KEY", "").strip()
    if not api_key:
        _log.info("website.image_generation.skipped", reason="no_image_provider_key")
        return None, "unavailable"
    model = image_model()
    started = time.monotonic()
    try:
        async with httpx.AsyncClient(timeout=timeout_seconds) as client:
            response = await client.post(
                f"{_GEMINI_BASE}/models/{model}:generateContent",
                headers={"x-goog-api-key": api_key, "Content-Type": "application/json"},
                json=gemini_image_body(prompt, aspect_ratio),
            )
        latency_ms = int((time.monotonic() - started) * 1000)
        if response.status_code >= 400:
            _log.warning(
                "website.image_generation.failed",
                provider="google",
                status_code=response.status_code,
                latency_ms=latency_ms,
                error=response.text[:400],
            )
            return None, _reason_for(response.status_code, response.text[:400])
        found = gemini_image_from(response.json())
        if found is None:
            _log.warning("website.image_generation.empty", provider="google", latency_ms=latency_ms)
            return None, "error"
        mime, data = found
        _log.info(
            "website.image_generation.ok",
            provider="google",
            model=model,
            latency_ms=latency_ms,
            bytes=len(data),
        )
        return GeneratedImage(
            mime_type=mime, bytes=data, model=model, latency_ms=latency_ms, prompt=prompt
        ), ""
    except Exception as exc:  # noqa: BLE001 — image gen must never fail the draft
        _log.warning("website.image_generation.error", provider="google", error=str(exc)[:400])
        return None, "error"


async def generate_image(
    prompt: str,
    *,
    aspect_ratio: str = "16:9",
    timeout_seconds: int = 60,
) -> tuple[GeneratedImage | None, str]:
    """(image, "") or (None, reason) — reason is a key of FAILURE_REASONS."""
    provider = image_provider()
    if provider == "gemini":
        return await _generate_gemini(
            prompt, aspect_ratio=aspect_ratio, timeout_seconds=timeout_seconds
        )
    image = await generate_image_bytes(prompt, aspect_ratio=aspect_ratio,
                                       timeout_seconds=timeout_seconds)
    return (image, "") if image else (None, "unavailable" if not image_generation_available() else "error")


async def generate_image_bytes(
    prompt: str,
    *,
    aspect_ratio: str = "16:9",
    timeout_seconds: int = 60,
) -> GeneratedImage | None:
    """Return generated bytes, or None when the key is missing or the provider fails."""
    provider = image_provider()
    if provider == "gemini":
        image, _ = await _generate_gemini(
            prompt, aspect_ratio=aspect_ratio, timeout_seconds=timeout_seconds
        )
        return image
    if provider not in {"xai", "grok"}:
        _log.info("website.image_generation.skipped", reason="no_image_provider")
        return None
    api_key = os.getenv("XAI_API_KEY", "").strip()
    if not api_key:
        _log.info("website.image_generation.skipped", reason="no_xai_api_key")
        return None
    model = image_model()
    started = time.monotonic()
    body: dict[str, Any] = {
        "model": model,
        "prompt": prompt,
        "n": 1,
        "aspect_ratio": aspect_ratio,
        "response_format": "b64_json",
    }
    try:
        async with httpx.AsyncClient(timeout=timeout_seconds) as client:
            response = await client.post(
                _XAI_IMAGES_URL,
                headers={
                    "Authorization": f"Bearer {api_key}",
                    "Content-Type": "application/json",
                },
                json=body,
            )
        latency_ms = int((time.monotonic() - started) * 1000)
        if response.status_code >= 400:
            _log.warning(
                "website.image_generation.failed",
                status_code=response.status_code,
                latency_ms=latency_ms,
                error=response.text[:400],
            )
            return None
        payload = response.json()
        rows = payload.get("data") if isinstance(payload, dict) else None
        if not isinstance(rows, list) or not rows:
            _log.warning("website.image_generation.empty", latency_ms=latency_ms)
            return None
        first = rows[0] if isinstance(rows[0], dict) else {}
        raw_b64 = first.get("b64_json")
        if isinstance(raw_b64, str) and raw_b64:
            return GeneratedImage(
                mime_type="image/jpeg",
                bytes=base64.b64decode(raw_b64),
                model=model,
                latency_ms=latency_ms,
                prompt=prompt,
            )
        url = first.get("url")
        if isinstance(url, str) and url.startswith("https://"):
            async with httpx.AsyncClient(timeout=timeout_seconds) as client:
                downloaded = await client.get(url)
            if downloaded.status_code == 200 and downloaded.content:
                return GeneratedImage(
                    mime_type=downloaded.headers.get("content-type", "image/jpeg").split(";")[0],
                    bytes=downloaded.content,
                    model=model,
                    latency_ms=latency_ms,
                    prompt=prompt,
                )
        _log.warning("website.image_generation.unusable_payload", latency_ms=latency_ms)
        return None
    except Exception as exc:  # noqa: BLE001 — image gen must never fail the draft
        _log.warning("website.image_generation.error", error=str(exc)[:400])
        return None
