"""Type-aware Grok image generation for Website and Offering media.

Doc 12 §12.6: AI never writes external URLs into content. Generated bytes are
persisted as `media_assets` and only the asset id is stored on sections /
offerings. Failure is non-fatal — the site stays editable without a broken
image URL.
"""

from __future__ import annotations

import base64
import os
import time
from dataclasses import dataclass
from typing import Any

import httpx

from platform_core.logging import get_logger

_log = get_logger("website.image_generation")

_XAI_IMAGES_URL = "https://api.x.ai/v1/images/generations"
_DEFAULT_IMAGE_MODEL = os.getenv("XAI_IMAGE_MODEL", "grok-imagine-image-2.0")

# Photorealistic, no text, no fake logos — the renderer already has type.
_SCENE_BY_FAMILY: dict[str, str] = {
    "food": "a neighbourhood restaurant or cafe: food, kitchen warmth, dining interior",
    "appointment": "a calm salon or clinic interior: chairs, tools, professional care",
    "membership": "a gym or studio: equipment, natural light, people-free space",
    "stay": "a hotel or homestay room: bed, window light, quiet interior",
    "retail": "a retail shop floor: products on shelves, warm lighting",
    "property": "a well-kept property exterior or living room, no signage",
    "professional": "a small professional studio or office, desks, natural light",
    "education": "a classroom or music/coaching room with instruments or desks",
    "repair": "a tradesperson's workspace: tools, van-workshop, practical light",
    "rental": "rental equipment or a venue interior, clean and usable",
    "general": "an independent local business interior, warm and specific",
}

_FAMILY_BY_TYPE: dict[str, str] = {
    "restaurant": "food",
    "cafe": "food",
    "food": "food",
    "salon": "appointment",
    "spa": "appointment",
    "clinic": "appointment",
    "gym": "membership",
    "studio": "membership",
    "hotel": "stay",
    "homestay": "stay",
    "retail": "retail",
    "grocery": "retail",
    "real_estate": "property",
    "professional": "professional",
    "agency": "professional",
    "coaching": "education",
    "education": "education",
    "repair": "repair",
    "rental": "rental",
}


@dataclass(frozen=True)
class GeneratedImage:
    mime_type: str
    bytes: bytes
    model: str
    latency_ms: int
    prompt: str


def family_for_business_type(business_type: str | None) -> str:
    key = (business_type or "other").strip().lower()
    return _FAMILY_BY_TYPE.get(key, "general")


def hero_prompt(*, display_name: str, business_type: str | None, description: str | None) -> str:
    family = family_for_business_type(business_type)
    scene = _SCENE_BY_FAMILY[family]
    extra = (description or "").strip()[:240]
    return (
        f"Photorealistic photograph for the homepage of {display_name}, "
        f"a {(business_type or 'local')} business. Show {scene}. "
        f"{extra} "
        "No text, no watermarks, no logos, no UI chrome, no people facing camera."
    )


def offering_prompt(
    *,
    display_name: str,
    business_type: str | None,
    title: str,
    description: str | None,
) -> str:
    family = family_for_business_type(business_type)
    extra = (description or "").strip()[:200]
    if family == "food":
        subject = f"a plated dish called {title}"
    elif family == "stay":
        subject = f"an accommodation room or unit called {title}"
    elif family in {"appointment", "professional", "repair"}:
        subject = f"the service '{title}' in a real workspace"
    elif family == "membership":
        subject = f"the class or plan '{title}' in a gym/studio setting"
    elif family == "retail":
        subject = f"the product '{title}' on a shop surface"
    else:
        subject = f"{title} as this business actually offers it"
    return (
        f"Photorealistic photograph for {display_name}: {subject}. {extra} "
        "No text, no watermarks, no logos, no price tags."
    )


def image_model() -> str:
    return os.getenv("XAI_IMAGE_MODEL", _DEFAULT_IMAGE_MODEL).strip() or _DEFAULT_IMAGE_MODEL


async def generate_image_bytes(
    prompt: str,
    *,
    aspect_ratio: str = "16:9",
    timeout_seconds: int = 60,
) -> GeneratedImage | None:
    """Return generated bytes, or None when the key is missing or the provider fails."""
    api_key = os.getenv("XAI_API_KEY", "").strip()
    if not api_key:
        _log.info("website.image_generation.skipped", reason="no_xai_api_key")
        return None
    model = image_model()
    started = time.monotonic()
    body: dict[str, Any] = {
        "model": model,
        "prompt": prompt,
        "n": 1,
        "aspect_ratio": aspect_ratio,
        "response_format": "b64_json",
    }
    try:
        async with httpx.AsyncClient(timeout=timeout_seconds) as client:
            response = await client.post(
                _XAI_IMAGES_URL,
                headers={
                    "Authorization": f"Bearer {api_key}",
                    "Content-Type": "application/json",
                },
                json=body,
            )
        latency_ms = int((time.monotonic() - started) * 1000)
        if response.status_code >= 400:
            _log.warning(
                "website.image_generation.failed",
                status_code=response.status_code,
                latency_ms=latency_ms,
                error=response.text[:400],
            )
            return None
        payload = response.json()
        rows = payload.get("data") if isinstance(payload, dict) else None
        if not isinstance(rows, list) or not rows:
            _log.warning("website.image_generation.empty", latency_ms=latency_ms)
            return None
        first = rows[0] if isinstance(rows[0], dict) else {}
        raw_b64 = first.get("b64_json")
        if isinstance(raw_b64, str) and raw_b64:
            return GeneratedImage(
                mime_type="image/jpeg",
                bytes=base64.b64decode(raw_b64),
                model=model,
                latency_ms=latency_ms,
                prompt=prompt,
            )
        url = first.get("url")
        if isinstance(url, str) and url.startswith("https://"):
            async with httpx.AsyncClient(timeout=timeout_seconds) as client:
                downloaded = await client.get(url)
            if downloaded.status_code == 200 and downloaded.content:
                return GeneratedImage(
                    mime_type=downloaded.headers.get("content-type", "image/jpeg").split(";")[0],
                    bytes=downloaded.content,
                    model=model,
                    latency_ms=latency_ms,
                    prompt=prompt,
                )
        _log.warning("website.image_generation.unusable_payload", latency_ms=latency_ms)
        return None
    except Exception as exc:  # noqa: BLE001 — image gen must never fail the draft
        _log.warning("website.image_generation.error", error=str(exc)[:400])
        return None
