"""Image generation for Website and Offering media.

Doc 12 §12.6: AI never writes external URLs into content. Generated bytes are
persisted as `media_assets` and only the asset id is stored on sections /
offerings. Failure is non-fatal — the site stays editable without a broken
image URL.

This module only talks to the image model. WHAT is drawn — and what may never
be drawn (the media truth policy) — is decided by the MediaDirector, and every
website prompt is written by `website.media_prompts` from the site's own shoot
brief. Logo prompts live here.

Provider: Gemini only (IMAGE_PROVIDER=gemini, the default, GEMINI_IMAGE_MODEL);
IMAGE_PROVIDER=none switches drawing off. A failed image is a missing image,
never a second paid call.
"""

from __future__ import annotations

import base64
import os
import time
from dataclasses import dataclass
from typing import Any

import httpx

from platform_core.ai_guard import guard_external_ai
from platform_core.logging import get_logger

_log = get_logger("website.image_generation")

_GEMINI_BASE = "https://generativelanguage.googleapis.com/v1beta"
GEMINI_IMAGE_MODEL = "gemini-3.1-flash-image"


@dataclass(frozen=True)
class GeneratedImage:
    mime_type: str
    bytes: bytes
    model: str
    latency_ms: int
    prompt: str


def logo_prompt(*, initial: str, primary: str | None) -> str:
    """A single-letter monogram: the one kind of logo a model draws reliably."""
    letter = (initial or "").strip()[:1].upper() or "A"
    colour = primary or "a deep, confident colour"
    return (
        f"A simple flat vector monogram logo: the single capital letter {letter}, "
        f"in {colour}, set inside a clean geometric shape, centred on a plain white "
        "background with generous padding. Balanced, minimal, timeless. Only that one "
        "letter — no other letters, words, slogans, gradients, mockups, shadows or 3D."
    )


def brand_logo_prompt(
    *, name: str, category: str = "", direction: str = "", palette: tuple[str, ...] = ()
) -> str:
    """A logo from brand context — never from the conversation transcript.

    The business name, what kind of business it is, the feel the owner asked
    for and the site's colours. Nothing the owner said about customers, prices
    or people reaches the image provider.
    """
    colours = ", ".join(c for c in palette if c) or "two harmonious brand colours"
    kind = f", a {category}" if category else ""
    feel = f" The feel: {direction[:160]}." if direction else " Warm, simple and trustworthy."
    return (
        f"Design a clean, modern logo for \"{name[:60]}\"{kind}. A simple flat vector mark with the "
        f"business name set in clear, correctly spelled lettering beside or below it.{feel} Use "
        f"{colours} on a plain white background, centred, with generous padding. No mockups, "
        "no photographs, no extra words, no taglines, no gradients, no 3D."
    )


def image_provider() -> str:
    return (os.getenv("IMAGE_PROVIDER") or "gemini").strip().lower()


def image_generation_available() -> bool:
    """Whether Gemini image generation is configured. No key, no button."""
    return image_provider() == "gemini" and bool(os.getenv("GEMINI_API_KEY", "").strip())


def image_model() -> str:
    return (os.getenv("GEMINI_IMAGE_MODEL") or GEMINI_IMAGE_MODEL).strip()


def gemini_image_body(prompt: str, aspect_ratio: str) -> dict[str, Any]:
    return {
        "contents": [{"role": "user", "parts": [{"text": prompt}]}],
        "generationConfig": {
            "responseModalities": ["IMAGE"],
            "imageConfig": {"aspectRatio": aspect_ratio},
        },
    }


def gemini_image_from(payload: Any) -> tuple[str, bytes] | None:
    """The first inline image in a generateContent response."""
    if not isinstance(payload, dict):
        return None
    for candidate in payload.get("candidates") or []:
        parts = ((candidate or {}).get("content") or {}).get("parts") or []
        for part in parts:
            inline = (part or {}).get("inlineData") or (part or {}).get("inline_data")
            if isinstance(inline, dict) and inline.get("data"):
                mime = str(inline.get("mimeType") or inline.get("mime_type") or "image/png")
                return mime, base64.b64decode(inline["data"])
    return None


# Why an image was not made, in terms an owner-facing message can use. A quota
# or billing refusal must never read like Locah misunderstanding the owner.
FAILURE_REASONS = {
    "unavailable": "Image generation isn't available on this environment right now.",
    "quota": "Image generation has reached its limit for now — try again later, or upload one.",
    "billing": "Image generation isn't enabled for this account yet — upload one, or try again "
               "once it's enabled.",
    "rejected": "The image provider declined this request. You can try again or upload one.",
    "error": "The picture couldn't be made this time. You can try again or upload one.",
}


def _reason_for(status: int, body: str) -> str:
    low = body.lower()
    if status == 429 or "quota" in low or "rate limit" in low:
        return "quota"
    if status in (402, 403) or "billing" in low or "credits" in low:
        return "billing"
    if status == 400:
        return "rejected"
    return "error"


async def _generate_gemini(
    prompt: str, *, aspect_ratio: str, timeout_seconds: int
) -> tuple[GeneratedImage | None, str]:
    api_key = os.getenv("GEMINI_API_KEY", "").strip()
    if not api_key:
        _log.info("website.image_generation.skipped", reason="no_image_provider_key")
        return None, "unavailable"
    # Outside the try below on purpose: a refused paid call must surface, not
    # read as an ordinary failed picture.
    guard_external_ai("image", "gemini", "image")
    model = image_model()
    started = time.monotonic()
    try:
        async with httpx.AsyncClient(timeout=timeout_seconds) as client:
            response = await client.post(
                f"{_GEMINI_BASE}/models/{model}:generateContent",
                headers={"x-goog-api-key": api_key, "Content-Type": "application/json"},
                json=gemini_image_body(prompt, aspect_ratio),
            )
        latency_ms = int((time.monotonic() - started) * 1000)
        if response.status_code >= 400:
            _log.warning(
                "website.image_generation.failed",
                provider="google",
                status_code=response.status_code,
                latency_ms=latency_ms,
                error=response.text[:400],
            )
            return None, _reason_for(response.status_code, response.text[:400])
        found = gemini_image_from(response.json())
        if found is None:
            _log.warning("website.image_generation.empty", provider="google", latency_ms=latency_ms)
            return None, "error"
        mime, data = found
        _log.info(
            "website.image_generation.ok",
            provider="google",
            model=model,
            latency_ms=latency_ms,
            bytes=len(data),
        )
        return GeneratedImage(
            mime_type=mime, bytes=data, model=model, latency_ms=latency_ms, prompt=prompt
        ), ""
    except Exception as exc:  # noqa: BLE001 — image gen must never fail the draft
        _log.warning("website.image_generation.error", provider="google", error=str(exc)[:400])
        return None, "error"


async def generate_image(
    prompt: str,
    *,
    aspect_ratio: str = "16:9",
    timeout_seconds: int = 60,
) -> tuple[GeneratedImage | None, str]:
    """(image, "") or (None, reason) — reason is a key of FAILURE_REASONS."""
    if image_provider() != "gemini":
        _log.info("website.image_generation.skipped", reason="no_image_provider")
        return None, "unavailable"
    return await _generate_gemini(prompt, aspect_ratio=aspect_ratio, timeout_seconds=timeout_seconds)


async def generate_image_bytes(
    prompt: str,
    *,
    aspect_ratio: str = "16:9",
    timeout_seconds: int = 60,
) -> GeneratedImage | None:
    """Return generated bytes, or None when the key is missing or the provider fails."""
    image, _ = await generate_image(prompt, aspect_ratio=aspect_ratio, timeout_seconds=timeout_seconds)
    return image
