"""Seventeen business owners for the interview evaluation (see interview_eval.py).

Sixteen trades from the Phase A brief, plus the real "Wift" transcript from
staging as the adversarial case. Openings are written the way owners actually
type — one in Tamil, one in Tamil-English. Every scripted quotation is checked
against the owner's message by `intel()`.
"""

from __future__ import annotations

from platform_testing.interview_eval import Persona, intel

MEAT_OPEN = ("We sell chicken, mutton, fish, crab and squid. Fish different varieties also there. "
             "People select the meat and kg and order on WhatsApp.")
REST_OPEN = ("Saffron & Salt is a South Indian restaurant in Anna Nagar. We're known for our Chettinad "
             "chicken, dosas and full meals. Most people walk in, some call to book a table for weekends.")
HOME_OPEN = ("Naan veetla irundhu home food pannuren. Sambar rice, kootu, poriyal, and Sunday chicken "
             "biryani. Customers WhatsApp-la order pannuvaanga, oru naal munnaadi.")
BAKE_OPEN = ("We are a small bakery in Adyar. Breads, puffs, cookies and custom cakes. People walk in, and "
             "cake orders come on WhatsApp.")
GYM_OPEN = "Grit Barbell Club is a strength gym in Velachery — powerlifting, strength classes and personal training."
SALON_OPEN = ("நான் சென்னையில் மிரர் அண்ட் மியூஸ் சலூன் நடத்துறேன். ஹேர் கட், பிரைடல் மேக்கப், ஃபேஷியல் "
              "எல்லாம் பண்றோம். கஸ்டமர்ஸ் அப்பாயிண்ட்மென்ட் புக் பண்ணனும்.")
DENT_OPEN = ("BrightSmile Dental is a dental clinic in T Nagar with two dentists. We do cleaning, braces, "
             "implants and root canal treatment.")
HOSP_OPEN = ("Meridian Care is a 120-bed multispeciality hospital in Tambaram — cardiology, orthopaedics, "
             "paediatrics and a 24-hour emergency department.")
HOTEL_OPEN = ("Kodai Pines is a 20-room resort in Kodaikanal with valley-view cottages, a restaurant and a "
              "campfire lawn.")
PROP_OPEN = ("Aranya Homes builds villas and apartments on OMR. We have three projects — Aranya Greens villas, "
             "Aranya Heights apartments and Aranya Meadows plots.")
TUIT_OPEN = "Apex Tuition Centre teaches maths and science for classes 8 to 12, plus JEE foundation, in Anna Nagar."
PHOTO_OPEN = ("Golden Hour is a wedding photography studio — candid weddings, pre-wedding shoots and wedding films "
              "across Tamil Nadu.")
PUMP_OPEN = ("Torque Flow supplies centrifugal pumps, valves and motors to factories and apartment builders "
             "around Chennai and Hosur.")
LOGI_OPEN = ("Swift Route is a logistics company — part-load and full truckload transport, plus warehousing, "
             "for businesses in South India.")
FLOR_OPEN = "Petal & Stem is a florist in Adyar — bouquets, flower baskets and wedding decoration."
INT_OPEN = "Studio Lumen does home interiors in Chennai — full-home interiors, modular kitchens and wardrobes."
WIFT_OPEN = ("Wift is a gym app, which allows user to track their exercises by adding exercies to routines.\n"
             "See analytics of their workouts and track their weights and stuff.")


PERSONAS: list[Persona] = [
    Persona(
        "meat-shop", "Ishant Proteins", "Meat shop", ("fresh_grocery", "meat_shop", "Meat shop"), "retail",
        intel(MEAT_OPEN,
              facts={"offerings": "chicken, mutton, fish, crab and squid",
                     "customer_actions": "People select the meat and kg and order on WhatsApp"},
              answered={"business.identity": "We sell chicken, mutton, fish, crab and squid",
                        "offerings.main": "chicken, mutton, fish, crab and squid",
                        "commerce.action": "order on WhatsApp", "offerings.units": "select the meat and kg"},
              patterns={"product_led": "We sell chicken, mutton, fish, crab and squid", "order_led": "order on WhatsApp"},
              catalogue=[{"group": "Chicken", "unknown": ["cuts"], "sold_by": "by weight (kg)"},
                         {"group": "Mutton", "unknown": ["cuts"], "sold_by": "by weight (kg)"},
                         {"group": "Fish & Seafood", "items": [{"name": "Fish"}, {"name": "Crab"}, {"name": "Squid"}],
                          "unknown": ["varieties"]}]),
        {
            "structure": intel("Chicken - curry cut, boneless and wings. Mutton - curry cut and chops. "
                               "Fish - seer fish, pomfret and prawns.",
                               answered={"offerings.structure": "Chicken - curry cut, boneless and wings"},
                               catalogue=[{"group": "Chicken", "items": [{"name": "Curry cut"}, {"name": "Boneless"},
                                                                         {"name": "Wings"}]},
                                          {"group": "Mutton", "items": [{"name": "Curry cut"}, {"name": "Chops"}]},
                                          {"group": "Fish & Seafood", "items": [{"name": "Seer fish"}, {"name": "Pomfret"},
                                                                                {"name": "Prawns"}]}]),
            "fulfilment": intel("We deliver around Nookampalayam and Perumbakkam, people can also pick up from the shop.",
                                answered={"fulfilment.mode": "We deliver around Nookampalayam and Perumbakkam",
                                          "fulfilment.area": "Nookampalayam and Perumbakkam"},
                                patterns={"local_delivery": "We deliver", "pickup": "pick up from the shop"}),
            "area": intel("Nookampalayam and Perumbakkam.",
                          answered={"fulfilment.area": "Nookampalayam and Perumbakkam"}),
            "contact": intel("Nookampalayam Road, Chennai. WhatsApp 8754722026.",
                             facts={"locations": "Nookampalayam Road, Chennai", "phone": "8754722026"},
                             answered={"contact.location": "Nookampalayam Road, Chennai",
                                       "contact.phone": "8754722026"}),
            "phone": intel("8754722026", facts={"phone": "8754722026"}, answered={"contact.phone": "8754722026"}),
            "story": intel("Fresh stock comes every morning and we cut only after the order. Family run for 8 years.",
                           answered={"brand.story": "Fresh stock comes every morning and we cut only after the order"}),
        },
        core={"business.identity", "offerings.main", "commerce.action", "offerings.structure", "fulfilment.mode",
              "contact.location"},
        actions={"order_whatsapp"}, tools={"offerings-catalog", "orders", "fulfilment"},
        never_tools={"bookings", "memberships", "quotes"}, follow_ups=(2, 5),
    ),
    Persona(
        "restaurant", "Saffron & Salt", "Restaurant", ("food_service", "restaurant", "Restaurant"), "restaurant",
        intel(REST_OPEN,
              facts={"description": "Saffron & Salt is a South Indian restaurant in Anna Nagar",
                     "offerings": "Chettinad chicken, dosas and full meals", "locations": "Anna Nagar",
                     "customer_actions": "some call to book a table for weekends"},
              answered={"business.identity": "South Indian restaurant in Anna Nagar",
                        "offerings.main": "Chettinad chicken, dosas and full meals",
                        "contact.location": "Anna Nagar", "commerce.action": "some call to book a table for weekends"},
              patterns={"appointment_led": "book a table", "walk_in": "Most people walk in"}),
        {
            "conversion": intel("People can book a table or order takeaway on the phone.",
                                answered={"commerce.action": "book a table or order takeaway on the phone"},
                                patterns={"pickup": "takeaway"}),
            "fulfilment": intel("Takeaway only, we don't deliver ourselves.",
                                answered={"fulfilment.mode": "Takeaway only"}, patterns={"pickup": "Takeaway"}),
            "contact": intel("Call us on 9840012345.", facts={"phone": "9840012345"},
                             answered={"contact.phone": "9840012345"}),
            "phone": intel("Call us on 9840012345.", facts={"phone": "9840012345"},
                           answered={"contact.phone": "9840012345"}),
            "story": intel("Our recipes are from my grandmother's Karaikudi kitchen.",
                           answered={"brand.story": "Our recipes are from my grandmother's Karaikudi kitchen"}),
        },
        core={"business.identity", "offerings.main", "commerce.action", "contact.location"},
        actions={"book_table", "book_call", "call", "visit"}, tools={"bookings"},
        never_tools={"memberships", "quotes"}, follow_ups=(1, 5),
    ),
    Persona(
        "home-food", "Nalla Veedu Kitchen", "Home food", ("home_food", "home_kitchen", "Home kitchen"), "restaurant",
        intel(HOME_OPEN,
              facts={"description": "Naan veetla irundhu home food pannuren",
                     "offerings": "Sambar rice, kootu, poriyal, and Sunday chicken biryani",
                     "customer_actions": "Customers WhatsApp-la order pannuvaanga"},
              answered={"business.identity": "Naan veetla irundhu home food pannuren",
                        "offerings.main": "Sambar rice, kootu, poriyal, and Sunday chicken biryani",
                        "commerce.action": "Customers WhatsApp-la order pannuvaanga"},
              patterns={"order_led": "order pannuvaanga", "made_to_order": "oru naal munnaadi"},
              language="ta_en"),
        {
            "fulfilment": intel("Veetla vandhu pickup pannalaam, 3 km kulla naan deliver pannuven.",
                                answered={"fulfilment.mode": "Veetla vandhu pickup pannalaam, 3 km kulla naan deliver pannuven",
                                          "fulfilment.area": "3 km kulla"},
                                patterns={"pickup": "pickup pannalaam", "local_delivery": "deliver pannuven"},
                                language="ta_en"),
            "contact": intel("Saibaba Colony, Coimbatore. Number 9894012345.",
                             facts={"locations": "Saibaba Colony, Coimbatore", "phone": "9894012345"},
                             answered={"contact.location": "Saibaba Colony, Coimbatore",
                                       "contact.phone": "9894012345"}, language="ta_en"),
            "story": intel("Ellaam en amma recipe, dhinamum fresh-aa samaippen.",
                           answered={"brand.story": "Ellaam en amma recipe, dhinamum fresh-aa samaippen"},
                           language="ta_en"),
        },
        core={"business.identity", "offerings.main", "commerce.action", "fulfilment.mode"},
        actions={"order_whatsapp"}, tools={"offerings-catalog", "orders"}, follow_ups=(2, 5), language="ta_en",
    ),
    Persona(
        "bakery", "Crumb & Co", "Bakery", ("food_service", "bakery", "Bakery"), "cafe",
        intel(BAKE_OPEN,
              facts={"description": "We are a small bakery in Adyar", "locations": "Adyar",
                     "offerings": "Breads, puffs, cookies and custom cakes",
                     "customer_actions": "People walk in, and cake orders come on WhatsApp"},
              answered={"business.identity": "a small bakery in Adyar",
                        "offerings.main": "Breads, puffs, cookies and custom cakes",
                        "commerce.action": "cake orders come on WhatsApp", "contact.location": "Adyar"},
              patterns={"walk_in": "People walk in", "made_to_order": "custom cakes", "order_led": "cake orders"}),
        {
            "customisation": intel("Yes, custom cakes for birthdays with name and photo, order two days before.",
                                   answered={"offerings.customisation": "custom cakes for birthdays with name and photo"}),
            "fulfilment": intel("Pickup from the shop, and we deliver cakes within Adyar.",
                                answered={"fulfilment.mode": "Pickup from the shop, and we deliver cakes within Adyar",
                                          "fulfilment.area": "within Adyar"},
                                patterns={"pickup": "Pickup from the shop", "local_delivery": "we deliver cakes"}),
            "contact": intel("Gandhi Nagar, Adyar. 9841098410.", facts={"locations": "Gandhi Nagar, Adyar",
                                                                          "phone": "9841098410"},
                             answered={"contact.location": "Gandhi Nagar, Adyar", "contact.phone": "9841098410"}),
            "phone": intel("9841098410", facts={"phone": "9841098410"}, answered={"contact.phone": "9841098410"}),
            "story": intel("Everything is baked fresh every morning, eggless options too.",
                           answered={"brand.story": "Everything is baked fresh every morning"}),
        },
        core={"business.identity", "offerings.main", "commerce.action", "offerings.customisation"},
        actions={"order_whatsapp", "visit"}, tools={"offerings-catalog", "orders"}, follow_ups=(2, 5),
    ),
    Persona(
        "gym", "Grit Barbell Club", "Gym", ("fitness", "gym", "Gym"), "gym",
        intel(GYM_OPEN,
              facts={"description": "Grit Barbell Club is a strength gym in Velachery", "locations": "Velachery",
                     "offerings": "powerlifting, strength classes and personal training"},
              answered={"business.identity": "a strength gym in Velachery",
                        "offerings.main": "powerlifting, strength classes and personal training",
                        "contact.location": "Velachery"},
              patterns={"runs_classes": "strength classes"}),
        {
            "conversion": intel("People WhatsApp us for a free trial session and then join a plan.",
                                facts={"customer_actions": "People WhatsApp us for a free trial session and then join a plan"},
                                answered={"commerce.action": "WhatsApp us for a free trial session and then join a plan"},
                                patterns={"membership_led": "join a plan"}),
            "plans": intel("Monthly 2500, quarterly 6500, and PT packs of 12 sessions.",
                           answered={"memberships.plans": "Monthly 2500, quarterly 6500, and PT packs of 12 sessions"},
                           patterns={"membership_led": "Monthly 2500"}),
            "bookings": intel("Trial sessions and PT slots, about an hour.",
                              answered={"bookings.format": "Trial sessions and PT slots, about an hour"}),
            "contact": intel("Velachery Main Road, Chennai. 9003012345.",
                             facts={"locations": "Velachery Main Road, Chennai", "phone": "9003012345"},
                             answered={"contact.location": "Velachery Main Road, Chennai", "contact.phone": "9003012345"}),
            "phone": intel("9003012345", facts={"phone": "9003012345"}, answered={"contact.phone": "9003012345"}),
            "story": intel("Coached by national-level lifters, no crowd, real barbells.",
                           answered={"brand.story": "Coached by national-level lifters"}),
        },
        core={"business.identity", "offerings.main", "commerce.action", "memberships.plans"},
        actions={"book_trial", "join", "whatsapp"}, tools={"memberships"}, follow_ups=(2, 6),
    ),
    Persona(
        "salon", "Mirror & Muse", "Salon (Tamil)", ("beauty", "salon", "Salon"), "salon",
        intel(SALON_OPEN,
              facts={"description": "நான் சென்னையில் மிரர் அண்ட் மியூஸ் சலூன் நடத்துறேன்.",
                     "offerings": "ஹேர் கட், பிரைடல் மேக்கப், ஃபேஷியல் எல்லாம் பண்றோம்.",
                     "customer_actions": "கஸ்டமர்ஸ் அப்பாயிண்ட்மென்ட் புக் பண்ணனும்."},
              answered={"business.identity": "நான் சென்னையில் மிரர் அண்ட் மியூஸ் சலூன் நடத்துறேன்.",
                        "offerings.main": "ஹேர் கட், பிரைடல் மேக்கப், ஃபேஷியல்",
                        "commerce.action": "கஸ்டமர்ஸ் அப்பாயிண்ட்மென்ட் புக் பண்ணனும்."},
              patterns={"appointment_led": "அப்பாயிண்ட்மென்ட் புக் பண்ணனும்"},
              catalogue=[{"group": "ஹேர் கட்"}, {"group": "பிரைடல் மேக்கப்"}, {"group": "ஃபேஷியல்"}],
              language="ta"),
        {
            "bookings": intel("பெரும்பாலும் ஒரு குறிப்பிட்ட ஸ்டைலிஸ்ட்டை கேப்பாங்க.",
                              answered={"services.providers": "பெரும்பாலும் ஒரு குறிப்பிட்ட ஸ்டைலிஸ்ட்டை கேப்பாங்க.",
                                        "bookings.format": "பெரும்பாலும் ஒரு குறிப்பிட்ட ஸ்டைலிஸ்ட்டை கேப்பாங்க."},
                              patterns={"provider_based": "ஸ்டைலிஸ்ட்டை"}, language="ta"),
            "contact": intel("அண்ணா நகர், சென்னை. 9876543210.", facts={"locations": "அண்ணா நகர், சென்னை",
                                                                         "phone": "9876543210"},
                             answered={"contact.location": "அண்ணா நகர், சென்னை", "contact.phone": "9876543210"},
                             language="ta"),
            "phone": intel("9876543210", facts={"phone": "9876543210"}, answered={"contact.phone": "9876543210"}),
        },
        core={"business.identity", "offerings.main", "commerce.action"},
        actions={"book_online"}, tools={"bookings"}, follow_ups=(1, 5), language="ta",
    ),
    Persona(
        "dental", "BrightSmile Dental", "Dental clinic", ("healthcare", "dental", "Dental clinic"), "clinic",
        intel(DENT_OPEN,
              facts={"description": "BrightSmile Dental is a dental clinic in T Nagar with two dentists",
                     "offerings": "cleaning, braces, implants and root canal treatment", "locations": "T Nagar"},
              answered={"business.identity": "a dental clinic in T Nagar",
                        "offerings.main": "cleaning, braces, implants and root canal treatment",
                        "contact.location": "T Nagar"},
              patterns={"provider_based": "two dentists", "service_led": "We do cleaning"}),
        {
            "conversion": intel("Patients call or WhatsApp to book an appointment.",
                                facts={"customer_actions": "Patients call or WhatsApp to book an appointment"},
                                answered={"commerce.action": "Patients call or WhatsApp to book an appointment"},
                                patterns={"appointment_led": "book an appointment"}),
            "bookings": intel("Yes, patients usually ask for Dr. Priya for braces; walk-ins are fine for check-ups.",
                              answered={"services.providers": "patients usually ask for Dr. Priya for braces",
                                        "bookings.format": "walk-ins are fine for check-ups"}),
            "contact": intel("Usman Road, T Nagar, Chennai. 9840554433.",
                             facts={"locations": "Usman Road, T Nagar, Chennai", "phone": "9840554433"},
                             answered={"contact.location": "Usman Road, T Nagar, Chennai", "contact.phone": "9840554433"}),
            "phone": intel("9840554433", facts={"phone": "9840554433"}, answered={"contact.phone": "9840554433"}),
        },
        core={"business.identity", "offerings.main", "commerce.action", "contact.location"},
        actions={"book_call", "book_whatsapp"}, tools={"bookings"},
        never_tools={"orders", "inventory", "fulfilment"}, follow_ups=(2, 5),
    ),
    Persona(
        "hospital", "Meridian Care", "Hospital", ("healthcare", "hospital", "Hospital"), "clinic",
        intel(HOSP_OPEN,
              facts={"description": "Meridian Care is a 120-bed multispeciality hospital in Tambaram",
                     "offerings": "cardiology, orthopaedics, paediatrics and a 24-hour emergency department",
                     "locations": "Tambaram"},
              answered={"business.identity": "a 120-bed multispeciality hospital in Tambaram",
                        "offerings.main": "cardiology, orthopaedics, paediatrics",
                        "contact.location": "Tambaram"}),
        {
            "conversion": intel("Patients book an OP appointment online or call the front desk.",
                                facts={"customer_actions": "Patients book an OP appointment online or call the front desk"},
                                answered={"commerce.action": "book an OP appointment online or call the front desk"},
                                patterns={"appointment_led": "book an OP appointment"}),
            "bookings": intel("OP consultations with a specific doctor, about 15 minutes.",
                              answered={"bookings.format": "OP consultations with a specific doctor, about 15 minutes"}),
            "contact": intel("GST Road, Tambaram. Front desk 04422334455.",
                             facts={"locations": "GST Road, Tambaram", "phone": "04422334455"},
                             answered={"contact.location": "GST Road, Tambaram", "contact.phone": "04422334455"}),
            "phone": intel("04422334455", facts={"phone": "04422334455"}, answered={"contact.phone": "04422334455"}),
        },
        core={"business.identity", "offerings.main", "commerce.action"},
        actions={"book_online", "book_call", "call"}, tools={"bookings"},
        never_tools={"orders", "inventory"}, follow_ups=(1, 5),
    ),
    Persona(
        "hotel", "Kodai Pines", "Resort", ("travel_stay", "resort", "Resort"), "hotel",
        intel(HOTEL_OPEN,
              facts={"description": "Kodai Pines is a 20-room resort in Kodaikanal",
                     "offerings": "valley-view cottages, a restaurant and a campfire lawn", "locations": "Kodaikanal"},
              answered={"business.identity": "a 20-room resort in Kodaikanal",
                        "offerings.main": "valley-view cottages, a restaurant and a campfire lawn",
                        "contact.location": "Kodaikanal"}),
        {
            "conversion": intel("Guests call or WhatsApp us to book, some come through travel sites. We'd like booking "
                                "requests on the website.",
                                facts={"customer_actions": "Guests call or WhatsApp us to book"},
                                answered={"commerce.action": "Guests call or WhatsApp us to book"},
                                patterns={"appointment_led": "WhatsApp us to book"}),
            "photos": intel("Yes, we have professional photos of the rooms.", media="will_upload_photos",
                            answered={"media.photos": "we have professional photos of the rooms"}),
            "bookings": intel("Rooms by the night, two-night minimum on weekends.",
                              answered={"bookings.format": "Rooms by the night, two-night minimum on weekends"}),
            "contact": intel("Near Upper Lake Road, Kodaikanal. 9443012345.",
                             facts={"locations": "Near Upper Lake Road, Kodaikanal", "phone": "9443012345"},
                             answered={"contact.location": "Near Upper Lake Road, Kodaikanal",
                                       "contact.phone": "9443012345"}),
            "phone": intel("9443012345", facts={"phone": "9443012345"}, answered={"contact.phone": "9443012345"}),
        },
        core={"business.identity", "offerings.main", "commerce.action", "media.photos"},
        actions={"book_call", "book_whatsapp", "book_online"}, tools={"bookings"}, follow_ups=(2, 6),
    ),
    Persona(
        "real-estate", "Aranya Homes", "Real estate developer", ("real_estate", "developer", "Property developer"),
        "professional_service",
        intel(PROP_OPEN,
              facts={"description": "Aranya Homes builds villas and apartments on OMR", "locations": "OMR",
                     "offerings": "Aranya Greens villas, Aranya Heights apartments and Aranya Meadows plots"},
              answered={"business.identity": "Aranya Homes builds villas and apartments on OMR",
                        "offerings.main": "Aranya Greens villas, Aranya Heights apartments and Aranya Meadows plots"},
              catalogue=[{"group": "Projects", "items": [{"name": "Aranya Greens"}, {"name": "Aranya Heights"},
                                                         {"name": "Aranya Meadows"}], "unknown": []}]),
        {
            "structure": intel("Aranya Greens is ready to move, Heights is under construction, Meadows is upcoming. "
                               "3 and 4 BHK villas, 2 and 3 BHK flats.",
                               answered={"offerings.structure": "Aranya Greens is ready to move"}),
            "conversion": intel("Buyers call or WhatsApp us to book a site visit.",
                                facts={"customer_actions": "Buyers call or WhatsApp us to book a site visit"},
                                answered={"commerce.action": "Buyers call or WhatsApp us to book a site visit"},
                                patterns={"lead_generation": "call or WhatsApp us"}),
            "contact": intel("Sholinganallur, OMR, Chennai. 9500012345.",
                             facts={"locations": "Sholinganallur, OMR, Chennai", "phone": "9500012345"},
                             answered={"contact.location": "Sholinganallur, OMR, Chennai", "contact.phone": "9500012345"}),
            "phone": intel("9500012345", facts={"phone": "9500012345"}, answered={"contact.phone": "9500012345"}),
            "photos": intel("We have renders and real photos of Aranya Greens.", media="will_upload_photos",
                            answered={"media.photos": "We have renders and real photos of Aranya Greens"}),
            "story": intel("14 projects delivered since 2009, RERA registered.",
                           answered={"brand.story": "14 projects delivered since 2009"}),
        },
        core={"business.identity", "offerings.main", "commerce.action", "offerings.structure"},
        actions={"book_site_visit"}, tools={"bookings"}, never_tools={"orders", "inventory"}, follow_ups=(2, 6),
    ),
    Persona(
        "tuition", "Apex Tuition Centre", "Tuition centre", ("education", "tuition_centre", "Tuition centre"),
        "education",
        intel(TUIT_OPEN,
              facts={"description": "Apex Tuition Centre teaches maths and science for classes 8 to 12",
                     "offerings": "maths and science for classes 8 to 12, plus JEE foundation", "locations": "Anna Nagar"},
              answered={"business.identity": "Apex Tuition Centre teaches maths and science",
                        "offerings.main": "maths and science for classes 8 to 12, plus JEE foundation",
                        "contact.location": "Anna Nagar"}),
        {
            "conversion": intel("Parents call or visit to enrol; we offer a free demo class first.",
                                facts={"customer_actions": "Parents call or visit to enrol"},
                                answered={"commerce.action": "Parents call or visit to enrol"},
                                patterns={"lead_generation": "Parents call"}),
            "plans": intel("Monthly fees, morning and evening batches.",
                           answered={"memberships.plans": "Monthly fees, morning and evening batches"}),
            "contact": intel("2nd Avenue, Anna Nagar, Chennai. 9884012345.",
                             facts={"locations": "2nd Avenue, Anna Nagar, Chennai", "phone": "9884012345"},
                             answered={"contact.location": "2nd Avenue, Anna Nagar, Chennai", "contact.phone": "9884012345"}),
            "phone": intel("9884012345", facts={"phone": "9884012345"}, answered={"contact.phone": "9884012345"}),
        },
        core={"business.identity", "offerings.main", "commerce.action"},
        actions={"book_trial", "join", "call", "visit"}, tools=set(), never_tools={"orders", "inventory"},
        follow_ups=(1, 5),
    ),
    Persona(
        "photographer", "Golden Hour", "Wedding photographer",
        ("creative", "wedding_photographer", "Wedding photographer"), "studio",
        intel(PHOTO_OPEN,
              facts={"description": "Golden Hour is a wedding photography studio",
                     "offerings": "candid weddings, pre-wedding shoots and wedding films"},
              answered={"business.identity": "a wedding photography studio",
                        "offerings.main": "candid weddings, pre-wedding shoots and wedding films"}),
        {
            "conversion": intel("Couples WhatsApp us to check dates and get a quote.",
                                facts={"customer_actions": "Couples WhatsApp us to check dates and get a quote"},
                                answered={"commerce.action": "Couples WhatsApp us to check dates and get a quote"},
                                patterns={"quote_led": "get a quote"}),
            "photos": intel("Yes, I can upload our best wedding photos.", media="will_upload_photos",
                            answered={"media.photos": "I can upload our best wedding photos"}),
            "contact": intel("Based in Coimbatore, we travel anywhere. 9994412345.",
                             facts={"locations": "Coimbatore", "phone": "9994412345"},
                             answered={"contact.location": "Coimbatore", "contact.phone": "9994412345"}),
            "phone": intel("9994412345", facts={"phone": "9994412345"}, answered={"contact.phone": "9994412345"}),
            "story": intel("Two photographers, 200 weddings, calm and unposed.",
                           answered={"brand.story": "Two photographers, 200 weddings, calm and unposed"}),
        },
        core={"business.identity", "offerings.main", "commerce.action", "media.photos"},
        actions={"check_dates", "request_quote", "whatsapp"}, tools={"quotes"},
        never_tools={"orders", "inventory", "memberships"}, follow_ups=(1, 5),
    ),
    Persona(
        "industrial", "Torque Flow Pumps", "Industrial pump supplier",
        ("industrial", "industrial_supplier", "Industrial supplier"), "professional_service",
        intel(PUMP_OPEN,
              facts={"description": "Torque Flow supplies centrifugal pumps, valves and motors",
                     "offerings": "centrifugal pumps, valves and motors"},
              answered={"business.identity": "Torque Flow supplies centrifugal pumps, valves and motors",
                        "offerings.main": "centrifugal pumps, valves and motors",
                        "b2b.customers": "factories and apartment builders around Chennai and Hosur"},
              patterns={"b2b": "to factories and apartment builders", "product_led": "supplies centrifugal pumps"}),
        {
            "b2b": intel("Mostly textile mills, food processing units and builders. Purchase teams send us an RFQ with specs.",
                         answered={"b2b.customers": "Mostly textile mills, food processing units and builders",
                                   "b2b.process": "Purchase teams send us an RFQ with specs"},
                         patterns={"quote_led": "send us an RFQ"}),
            "conversion": intel("Buyers should send an RFQ from the website or call our sales team.",
                                facts={"customer_actions": "Buyers should send an RFQ from the website or call our sales team"},
                                answered={"commerce.action": "send an RFQ from the website or call our sales team"},
                                patterns={"quote_led": "send an RFQ"}),
            "fulfilment": intel("We dispatch across Tamil Nadu by our own trucks.",
                                answered={"fulfilment.mode": "We dispatch across Tamil Nadu by our own trucks",
                                          "fulfilment.area": "across Tamil Nadu"},
                                patterns={"delivery": "our own trucks"}),
            "contact": intel("Ambattur Industrial Estate, Chennai. 9444012345.",
                             facts={"locations": "Ambattur Industrial Estate, Chennai", "phone": "9444012345"},
                             answered={"contact.location": "Ambattur Industrial Estate, Chennai",
                                       "contact.phone": "9444012345"}),
            "phone": intel("9444012345", facts={"phone": "9444012345"}, answered={"contact.phone": "9444012345"}),
        },
        core={"business.identity", "offerings.main", "commerce.action", "b2b.customers"},
        actions={"request_quote"}, tools={"quotes"}, never_tools={"bookings", "memberships"}, follow_ups=(2, 6),
    ),
    Persona(
        "logistics", "Swift Route Logistics", "Logistics", ("logistics", "trucking", "Trucking"), "professional_service",
        intel(LOGI_OPEN,
              facts={"description": "Swift Route is a logistics company",
                     "offerings": "part-load and full truckload transport, plus warehousing"},
              answered={"business.identity": "Swift Route is a logistics company",
                        "offerings.main": "part-load and full truckload transport, plus warehousing",
                        "b2b.customers": "for businesses in South India"},
              patterns={"b2b": "for businesses in South India", "service_led": "truckload transport"}),
        {
            "conversion": intel("Businesses call or WhatsApp us for a quote, then book a pickup.",
                                facts={"customer_actions": "Businesses call or WhatsApp us for a quote, then book a pickup"},
                                answered={"commerce.action": "call or WhatsApp us for a quote, then book a pickup"},
                                patterns={"quote_led": "for a quote"}),
            "fulfilment": intel("We cover Chennai, Bengaluru, Coimbatore and Hyderabad routes.",
                                answered={"fulfilment.area": "Chennai, Bengaluru, Coimbatore and Hyderabad routes"}),
            "area": intel("We cover Chennai, Bengaluru, Coimbatore and Hyderabad routes.",
                          answered={"fulfilment.area": "Chennai, Bengaluru, Coimbatore and Hyderabad routes"}),
            "b2b": intel("FMCG distributors, textile exporters and e-commerce sellers.",
                         answered={"b2b.customers": "FMCG distributors, textile exporters and e-commerce sellers"}),
            "contact": intel("Madhavaram, Chennai. 9345012345.", facts={"locations": "Madhavaram, Chennai",
                                                                          "phone": "9345012345"},
                             answered={"contact.location": "Madhavaram, Chennai", "contact.phone": "9345012345"}),
            "phone": intel("9345012345", facts={"phone": "9345012345"}, answered={"contact.phone": "9345012345"}),
        },
        core={"business.identity", "offerings.main", "commerce.action"},
        actions={"request_quote", "call", "whatsapp"}, tools={"quotes"}, never_tools={"orders", "inventory"},
        follow_ups=(1, 6),
    ),
    Persona(
        "florist", "Petal & Stem", "Florist", ("events", "florist", "Florist"), "other",
        intel(FLOR_OPEN,
              facts={"description": "Petal & Stem is a florist in Adyar", "locations": "Adyar",
                     "offerings": "bouquets, flower baskets and wedding decoration"},
              answered={"business.identity": "a florist in Adyar",
                        "offerings.main": "bouquets, flower baskets and wedding decoration",
                        "contact.location": "Adyar"},
              patterns={"product_led": "bouquets, flower baskets"}),
        {
            "conversion": intel("People order bouquets on WhatsApp or call, and wedding enquiries come on WhatsApp.",
                                facts={"customer_actions": "People order bouquets on WhatsApp or call"},
                                answered={"commerce.action": "People order bouquets on WhatsApp or call"},
                                patterns={"order_led": "order bouquets"}),
            "fulfilment": intel("Same-day bouquet delivery across South Chennai, and pickup from the shop.",
                                answered={"fulfilment.mode": "Same-day bouquet delivery across South Chennai, and pickup from the shop",
                                          "fulfilment.area": "across South Chennai"},
                                patterns={"local_delivery": "bouquet delivery", "pickup": "pickup from the shop"}),
            "contact": intel("LB Road, Adyar, Chennai. 9500098765.", facts={"locations": "LB Road, Adyar, Chennai",
                                                                              "phone": "9500098765"},
                             answered={"contact.location": "LB Road, Adyar, Chennai", "contact.phone": "9500098765"}),
            "phone": intel("9500098765", facts={"phone": "9500098765"}, answered={"contact.phone": "9500098765"}),
            "photos": intel("Yes, lots of photos of our bouquets and weddings.", media="will_upload_photos",
                            answered={"media.photos": "lots of photos of our bouquets and weddings"}),
        },
        core={"business.identity", "offerings.main", "commerce.action", "fulfilment.mode"},
        actions={"order_whatsapp", "order_call"}, tools={"offerings-catalog", "orders"},
        never_tools={"memberships"}, follow_ups=(2, 5),
    ),
    Persona(
        "interiors", "Studio Lumen Interiors", "Interior designer",
        ("design_build", "interior_designer", "Interior designer"), "studio",
        intel(INT_OPEN,
              facts={"description": "Studio Lumen does home interiors in Chennai", "locations": "Chennai",
                     "offerings": "full-home interiors, modular kitchens and wardrobes"},
              answered={"business.identity": "Studio Lumen does home interiors in Chennai",
                        "offerings.main": "full-home interiors, modular kitchens and wardrobes",
                        "contact.location": "Chennai"}),
        {
            "conversion": intel("Clients call or WhatsApp us for a free consultation, then we visit the site.",
                                facts={"customer_actions": "Clients call or WhatsApp us for a free consultation"},
                                answered={"commerce.action": "call or WhatsApp us for a free consultation"},
                                patterns={"lead_generation": "call or WhatsApp us", "project_based": "we visit the site"}),
            "photos": intel("Yes, I have photos of 30 finished homes.", media="will_upload_photos",
                            answered={"media.photos": "I have photos of 30 finished homes"}),
            "contact": intel("Nungambakkam, Chennai. 9840123456.", facts={"locations": "Nungambakkam, Chennai",
                                                                            "phone": "9840123456"},
                             answered={"contact.location": "Nungambakkam, Chennai", "contact.phone": "9840123456"}),
            "phone": intel("9840123456", facts={"phone": "9840123456"}, answered={"contact.phone": "9840123456"}),
            "story": intel("Designs that are practical for Indian families, delivered in 45 days.",
                           answered={"brand.story": "Designs that are practical for Indian families"}),
        },
        core={"business.identity", "offerings.main", "commerce.action", "media.photos"},
        actions={"book_consultation"}, tools={"leads"}, never_tools={"orders", "inventory"}, follow_ups=(1, 5),
    ),
    Persona(
        "wift-app", "Wift", "Fitness app (adversarial, real transcript)", None, "not_sure",
        intel(WIFT_OPEN,
              facts={"description": "Wift is a gym app, which allows user to track their exercises by adding exercies to routines."},
              answered={"business.identity": "Wift is a gym app"}),
        {
            "offer": intel("See the analytics about weight,streak and all.\nthen they mut be able to start workouts.\nAnd add exercies"),
            "conversion": intel("They must be able to order a equipment, book slots for trainsers, call",
                                facts={"customer_actions": "They must be able to order a equipment, book slots for trainsers, call"},
                                answered={"commerce.action": "order a equipment, book slots for trainsers, call"}),
            "contact": intel("GYm equipment, available trainers, dumbells,contact section"),
            "phone": intel("GYm equipment, available trainers, dumbells,contact section"),
            "fulfilment": intel("only deliver"),
            "area": intel("All india"),
            "story": intel("Freshness and energy"),
        },
        core={"business.identity"}, actions={"order_online", "book_online", "call"}, tools=set(), follow_ups=(1, 6),
    ),
]
