"""Render docs/current-build/business-os-implementation-ledger.md from the rows.

    uv run python -m tools.ledger.render            # write the ledger
    uv run python -m tools.ledger.render --gate P1  # print one phase's gate counts

The gate counts printed at the top of the ledger are computed here from the
rows, so they cannot drift from the rows themselves.
"""

from __future__ import annotations

import argparse
import sys
from collections import Counter
from pathlib import Path

from tools.ledger import rows_ai, rows_commerce, rows_engage, rows_foundation, rows_governance
from tools.ledger import rows_operate, rows_playbooks
from tools.ledger import progress
from tools.ledger.model import PHASES, STATUSES, Row, Section

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "docs" / "current-build" / "business-os-implementation-ledger.md"

SECTIONS: list[Section] = [
    *rows_foundation.SECTIONS,
    *rows_commerce.SECTIONS,
    *rows_engage.SECTIONS,
    *rows_operate.SECTIONS,
    *rows_ai.SECTIONS,
    *rows_playbooks.SECTIONS,
    *rows_governance.SECTIONS,
]

COLUMNS = ("ID", "PH", "SOURCE SECTION", "CAPABILITY", "MODULE KEY", "EXISTING / EXTEND / NEW / FUTURE",
           "CURRENT CODE STATUS", "DATABASE", "SERVICE/API", "PERMISSIONS/RLS", "WORKSPACE SURFACE",
           "CUSTOMER SURFACE", "WEBSITE CONTRIBUTION", "ROLE SURFACE", "AUTOMATION", "INTEGRATION",
           "TEST STATUS", "FINAL STATUS")


def _apply_progress() -> None:
    by_id = {row.id: row for s in SECTIONS for row in s.rows}
    for rid, change in progress.UPDATES.items():
        row = by_id.get(rid)
        if row is None:
            raise SystemExit(f"progress.py names unknown ledger id {rid}")
        for key, value in change.items():
            setattr(row, key, value)
        row.__post_init__()
    for d in rows_governance.DECISIONS:
        if d.id in progress.RESOLVED_DECISIONS:
            d.state = "RESOLVED"
            d.note = progress.RESOLVED_DECISIONS[d.id]


_apply_progress()


def all_rows() -> list[Row]:
    rows = [row for s in SECTIONS for row in s.rows]
    seen: set[str] = set()
    for row in rows:
        if row.id in seen:
            raise SystemExit(f"duplicate ledger id {row.id}")
        seen.add(row.id)
    return rows


def _cell(text: str) -> str:
    return text.replace("|", "\\|").replace("\n", " ")


def gate(phase: str) -> Counter[str]:
    return Counter(r.status for r in all_rows() if r.phase == phase)


def render() -> str:
    out: list[str] = []
    out.append("# LOCAH Business OS — implementation ledger\n\n")
    out.append(
        "Generated by `uv run python -m tools.ledger.render` from `tools/ledger/rows_*.py`. "
        "Edit the rows, never this file.\n\n"
    )
    out.append("\n" + "## Sources and authority\n" + "\n")
    out.append(
        "| Source | File | Size | Read |\n| --- | --- | --- | --- |\n"
        "| LOCAH Business OS Guide (PDF, Sep 2026) | `Documentations/LOCAH_Business_OS_Guide.pdf` | 1,595,983 bytes · 29 pages | complete text + page images where diagrams |\n"
        "| LOCAH — Business Capability Universe (MD, 24 Sep 2026) | `Documentations/LOCAH — Business Capability Universe.md` | 162,053 bytes · 1,540 lines | complete |\n\n"
    )
    out.append(
        "Authority: founder instructions (Phase B prompt, 2026-09-27) → PDF → MD → accepted implementation → "
        "repository → Documentations 01–12 (historical). The PDF replaces the MD's Razorpay references with Cashfree; "
        "the founder froze the existing Razorpay code and deferred the Cashfree adapter.\n\n"
    )
    out.append(
        "Baseline audited: `main` @ `0c56419` — 45 migrations, 79 tables, 146 RLS policies, "
        "832 backend tests passing on the RLS-enforcing `platform_api` role, web typecheck green.\n"
    )
    out.append("\n" + "## Status vocabulary\n" + "\n")
    out.append(
        "- **COMPLETE** — database, service/API, permissions/RLS, the surfaces the capability needs, and tests all exist and pass.\n"
        "- **PARTIAL** — some layers exist; the row says what is missing.\n"
        "- **NOT_STARTED** — nothing of the capability exists yet.\n"
        "- **ACTIVATION_REQUIRED** — everything LOCAH can build is built or the remainder needs an external account, provider, device, pilot or decision.\n"
        "- **FUTURE** — the source marks it FUTURE / P6; not built, not claimed.\n\n"
        "Cells: ✓ built and exercised by a test here · ◐ partly built · ✗ not built · — not applicable. "
        "PH is the source phase (P0 = First Launch, X = cross-cutting rule).\n"
    )

    out.append("\n" + "## Gate summary by phase\n" + "\n")
    out.append("| Phase | Total | " + " | ".join(STATUSES) + " |\n| --- | --- | " + " | ".join("---" for _ in STATUSES) + " |\n")
    totals: Counter[str] = Counter()
    for ph in PHASES:
        c = gate(ph)
        n = sum(c.values())
        if not n:
            continue
        totals.update(c)
        out.append(f"| {ph} | {n} | " + " | ".join(str(c.get(s, 0)) for s in STATUSES) + " |\n")
    out.append(f"| **All** | **{sum(totals.values())}** | " + " | ".join(f"**{totals.get(s, 0)}**" for s in STATUSES) + " |\n")
    decisions = rows_governance.DECISIONS
    out.append(
        f"\nOpen decisions: {sum(1 for d in decisions if d.state == 'OPEN_DECISION')} of {len(decisions)} · "
        f"Verify-at-build items: {len(rows_governance.VERIFY)}\n"
    )

    out.append("\n" + "## Contents\n" + "\n")
    for s in SECTIONS:
        out.append(f"- {s.title} ({len(s.rows)})\n")
    out.append("- Open decisions (MD §28.1)\n- Verify at build (MD §28.2)\n")

    for s in SECTIONS:
        out.append(f"\n## {s.title}\n\n")
        if s.intro:
            out.append(s.intro + "\n\n")
        out.append("| " + " | ".join(COLUMNS) + " |\n")
        out.append("| " + " | ".join("---" for _ in COLUMNS) + " |\n")
        for r in s.rows:
            cells = (r.id, r.phase, r.src, r.cap, r.mod, r.kind, r.code, r.db, r.svc, r.perm, r.ws,
                     r.cust, r.web, r.role, r.auto, r.integ, r.test, f"**{r.status}**")
            out.append("| " + " | ".join(_cell(c) for c in cells) + " |\n")

    out.append("\n## Open decisions (MD §28.1 + founder)\n\n| ID | Phase | Decision | State | Effect |\n| --- | --- | --- | --- | --- |\n")
    for d in decisions:
        out.append(f"| {d.id} | {d.phase} | {_cell(d.text)} | **{d.state}** | {_cell(d.note)} |\n")
    out.append("\n## Verify at build (MD §28.2)\n\nChecked against authoritative sources only when implementation reaches the item.\n\n"
               "| ID | Topic | Confirm | Section | State | Note |\n| --- | --- | --- | --- | --- | --- |\n")
    for v in rows_governance.VERIFY:
        out.append(f"| {v.id} | {v.topic} | {_cell(v.confirm)} | {v.src} | **{v.state}** | {_cell(v.note)} |\n")
    return "".join(out)


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--gate", help="print the gate counts for one phase")
    args = ap.parse_args(argv)
    if args.gate:
        c = gate(args.gate)
        print(f"TOTAL ITEMS IN {args.gate}: {sum(c.values())}")
        for s in STATUSES:
            print(f"{s}: {c.get(s, 0)}")
        for r in all_rows():
            if r.phase == args.gate and r.status == "NOT_STARTED":
                print(f"  NOT_STARTED {r.id} {r.cap[:90]}")
        return 0
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(render(), encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)} ({len(all_rows())} rows)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
