"""Foundation rows: founder requirements, principles, classification, packs,
primitives, surfaces and roles. Sources: MD §2–§5, §7, §22, §24; PDF §1–§5."""

from __future__ import annotations

from tools.ledger.model import Section, r

S = "NOT_STARTED"
P = "PARTIAL"
C = "COMPLETE"
A = "ACTIVATION_REQUIRED"
F = "FUTURE"

founder = Section(
    "A. Founder instructions (authority 1) and PDF product model",
    "Requirements stated in the Phase B founder prompt and the PDF's product model. "
    "These sit above the MD in the authority order.",
    [
        r("FD-01", "P1", "Founder §12 · PDF §1", "One LOCAH identity for customers across every business; tenant sites show Sign in / My orders / My bookings on that identity; guest flows stay", "platform", "EXTEND", P,
          "platform_identities + Supabase auth shared by all surfaces; guest checkout/booking exist; tenant site has no sign-in entry or 'my' pages",
          db="✓ platform_identities", svc="◐ /v1/me", perm="✓", ws="—", cust="◐ /activity only", web="✗ no sign-in on site", role="—", test="◐ test_identity"),
        r("FD-02", "P1", "Founder §13 · MD §7.1", "My Activity across businesses: orders, bookings, memberships, deliveries, quotes, payments, invoices, reviews, portal items — only modules the customer used", "platform", "EXTEND", P,
          "consumer_activity_projections + /activity page cover orders/bookings; no memberships/quotes/invoices/reviews/deliveries",
          db="◐", svc="◐ consumer_activity", cust="◐ /activity", test="◐ test_my_activity"),
        r("FD-03", "P1", "Founder §14–15", "Website Builder is module-aware: each operational module contributes semantic site capabilities, placed by the CreativeDirector; only ready modules expose actions", "website", "EXTEND", P,
          "sections exist for menu/rooms/plans/classes/products/enquiry + /checkout + /book + /track; not driven by module readiness per capability",
          db="✓ website_sections", svc="◐ composition", web="◐", test="◐ test_website_composition"),
        r("FD-04", "P1", "Founder §15", "Website changes when modules change (gym adds Memberships+Bookings → Plans/Join/Book trial/Classes/My membership appear without rebuild)", "website", "NEW", S,
          "no module-state → site capability recomposition", web="✗"),
        r("FD-05", "P1", "Founder §16 · PDF §1", "Marketplace customer actions (Order/Book/Join/Request quote/Enquire/Visit/Call/WhatsApp) come from real module readiness, never category defaults", "marketplace", "EXTEND", P,
          "marketplace projections exist; action set not derived from module readiness", db="✓ marketplace_business_projections", svc="◐", cust="◐ /marketplace/[slug]"),
        r("FD-06", "P1", "Founder §50 · MD §21 amendment", "Module discovery: what it does, why recommended, customer capability, staff capability, setup remaining; enabled ≠ configured ≠ ready ≠ permitted", "core-module-management", "EXTEND", P,
          "business_module_states has enabled/configuring/ready/active; /modules pages exist; no per-module explanation of customer/staff capability or setup checklist",
          db="✓ business_module_states", svc="◐ business_entitlements", ws="◐ /modules", test="◐ test_business_modules_ux"),
        r("FD-07", "P1", "Founder §20 · MD §7.3", "Owner adds a staff member with a role template + scope and issues login credentials (invite/one-time activation); staff sign in to their surface", "team", "EXTEND", P,
          "business_invitations + accept flow + templates exist; no role-template/scope picker matching §7.2, no surface routing after login",
          db="✓ business_invitations", svc="✓ invitation", ws="◐ /team", test="✓ test_invitation_engine"),
        r("FD-08", "P1", "PDF §3", "Workspace navigation: 12 stable areas (Home, Business Presence, Sell/Serve/Operate, Offerings, Customers, Money, Team, Reach, Insights, AI Employees, Modules & Integrations, Settings); children dynamic by module/role/scope/location", "core-workspace", "EXTEND", P,
          "sidebar = Core list + flat module list; not the 12-area model; not role-aware",
          ws="◐ AppSidebar"),
        r("FD-09", "P1", "PDF §3 · MD §7.2", "Home answers the role's question (owner: needs you now/today/setup next; manager; front desk; provider; cashier; dispatcher; accountant) from real data", "core-workspace", "EXTEND", P,
          "owner home exists; no role-specific homes", ws="◐ /b/[id]"),
        r("FD-10", "P1", "PDF §4 note", "A module is never presented as working until data, API, permissions and real UI are complete (readiness gate on every surface)", "core-module-management", "EXTEND", P,
          "module_states gate the sidebar; site/marketplace not gated per capability", ws="◐", web="◐"),
        r("FD-11", "P1", "PDF §12 · Founder §56", "Payments are provider-neutral: modules depend on a payment domain; Razorpay code preserved but not extended; Cashfree adapter later", "payments", "EXTEND", P,
          "payment_attempts/refunds/webhook_receipts are generic; provider_adapter branches on 'stub'/'razorpay'; merchant onboarding is Razorpay Route",
          db="✓", svc="◐ provider_adapter", integ="◐ razorpay (frozen)", test="✓ test_payments_kernel"),
        r("FD-12", "P1", "PDF §12", "Merchant money (customer→business) and platform billing (business→LOCAH) never share a ledger", "payments", "EXISTING", P,
          "commercial_entitlements is separate from payments_*; no platform-billing transactions table", db="◐"),
        r("FD-13", "P1", "PDF §12", "Browser callbacks are never payment truth; provider verification/webhook decides final state", "payments", "EXISTING", C,
          "webhooks_payments router + payment_webhook service; status only moves on verified webhook",
          db="✓ payments_webhook_receipts", svc="✓", test="✓ test_payments_kernel"),
        r("FD-14", "P0", "PDF §2", "Owner journey: talk → understand → build → run (interview, readiness, Build my Website, Keep refining, understanding panel)", "interview", "EXISTING", C,
          "Phase A shipped and verified (docs/phase-a/PHASE-A.md)", svc="✓", web="✓", test="✓ interview eval, flows A–L"),
        r("FD-15", "P1", "Founder §53 · MD §2 r12", "Workspace UX: progressive disclosure, empty states, setup states, mobile, business-aware terminology; owner never sees JSON", "core-workspace", "EXTEND", P,
          "Phase A UI quality; module pages are basic admin tables", ws="◐"),
    ],
)

principles = Section(
    "B. Design principles (MD §2) — cross-cutting rules every module must satisfy",
    "Counted under phase X. A principle is COMPLETE only when the code enforces it everywhere it applies.",
    [
        r("PR-01", "X", "MD §2 r1 · PDF §1", "One Business OS, many views — no vertical app; one backend", "platform", "EXISTING", C,
          "single API/worker/db; verticals are configuration", test="✓ architecture"),
        r("PR-02", "X", "MD §2 r2", "Category is guidance, not an allowlist — any business may enable any existing module", "entitlements", "EXTEND", P,
          "entitlements resolve per plan/module; business_type profiles still gate some defaults"),
        r("PR-03", "X", "MD §2 r3", "Traits decide, names don't", "catalog", "NEW", S, "no trait → module rules"),
        r("PR-04", "X", "MD §2 r4", "Deterministic first, AI second (mapping, tax, stock maths, BOM, renewals, prices are code)", "platform", "EXISTING", P,
          "Phase A deterministic fallbacks; new maths not built yet"),
        r("PR-05", "X", "MD §2 r5", "AI employees are staff: same permission engine/audit as humans, actor_type ai_employee; money/refunds/spend/deletions/POs above limit need owner approval", "ai-employees", "NEW", S, "no ai_employee actor"),
        r("PR-06", "X", "MD §2 r6", "One source of truth per data family for every connector", "connectors", "NEW", S, "no connector hub"),
        r("PR-07", "X", "MD §2 r7", "Honesty: no fabricated data, no fake features, deferred modules invisible, AI output labelled draft until accepted", "platform", "EXISTING", P,
          "Phase A truth rule; module readiness gating incomplete (FD-10)"),
        r("PR-08", "X", "MD §2 r8", "Tenant isolation unchanged: business_id = current_business_id(); cross-business records live on ChitBridge per-party copies", "platform", "EXISTING", C,
          "every tenant table has RLS; test_rls_isolation runs as platform_api", test="✓ test_rls_isolation"),
        r("PR-09", "X", "MD §2 r9", "Built for real devices: POS, crew app, attendance work on entry-level Android over patchy 4G with an offline queue", "pos/crew", "NEW", S, "no offline surfaces"),
        r("PR-10", "X", "MD §2 r10", "India-first defaults: INR, GST, UPI, WhatsApp-first, English+Tamil+Hindi, DPDP consent records", "platform", "EXTEND", P,
          "INR default; English UI only; no consent store"),
        r("PR-11", "X", "MD §2 r11", "Every automation idempotent, visible in owner activity log, off switch, via outbox/jobs", "automation", "EXTEND", P,
          "outbox/jobs idempotent; no owner-visible automation log or per-automation switch"),
        r("PR-12", "X", "MD §2 r12", "The owner never sees JSON (every module's settings are forms)", "platform", "EXISTING", P, "website editor structured; module config forms missing"),
        r("PR-13", "X", "MD §2 r13", "Every metered cost is metered per business with cap and pass-through pricing (WhatsApp, voice, Maps, tokens)", "usage-meters", "EXTEND", P,
          "generation_provider_usage records AI generation only; no generic meters/caps"),
    ],
)

classification = Section(
    "C. Classification: category, subcategory, traits, org shape (MD §4, §22; PDF §17)",
    "P1-01 scope.",
    [
        r("TX-01", "P1", "MD §4.1", "Search-first picker: one box, ~500 subcategory labels + synonyms, spelling-tolerant, deterministic", "catalog", "EXTEND", P,
          "taxonomy.search deterministic + synonyms; label count below source intent until all subcategories carried", svc="✓ /v1/taxonomy", web="✓ /start", test="✓ test_business_discovery"),
        r("TX-02", "P1", "MD §4.1", "Grid second: 12 most-chosen categories as tiles, then 'See all 32'", "catalog", "EXISTING", P,
          "tile flag on categories; tile count not verified as 12", web="◐"),
        r("TX-03", "P1", "MD §4.1", "No match → describe in a sentence → one AI call proposes category/subcategory/traits → owner confirms, never auto-saved", "catalog", "EXTEND", P,
          "interview infers category (Phase A) and the owner corrects it; traits not proposed", svc="◐ interview", test="✓ replay"),
        r("TX-04", "P1", "MD §4.1 · §4.4", "business_type kept as website_template_key; First Launch 14 types mapped to categories", "catalog", "EXISTING", P,
          "Category.template carries legacy business_type; no website_template_key naming", db="◐ businesses.business_type"),
        r("TX-05", "P1", "MD §4.2 · PDF §17", "32 selectable categories + Other, every listed subcategory selectable", "catalog", "EXISTING", P,
          "32 + other in taxonomy.py; subcategory completeness vs §4.2 to verify per row in fixtures", svc="✓", test="◐"),
        r("TX-06", "P1", "MD §4.3", "Trait group Buyer: b2c, b2b (both = hybrid); b2b → quotes, invoicing (B2B GST), ledger, trade-network", "catalog", "EXTEND", P, "traits exist; no switch-on rules"),
        r("TX-07", "P1", "MD §4.3", "Trait group Offer: sells_products/services/access; products → offerings-catalog, orders; access → memberships", "catalog", "EXTEND", P, "traits exist; no rules"),
        r("TX-08", "P1", "MD §4.3", "Trait group Transact: order/booking/quote/enquiry/subscription/project/donation_led → orders/bookings/quotes/leads/memberships/projects/donations", "catalog", "EXTEND", P, "traits exist; no rules"),
        r("TX-09", "P1", "MD §4.3", "Trait group Booking kind: appointment/table/stay/class/rental/site_visit/event_date → bookings mode; stay → tasks; rental → handover checklists", "catalog", "EXTEND", P, "traits exist; no rules"),
        r("TX-10", "P1", "MD §4.3", "Trait group Fulfilment: walk_in/pickup/local_delivery/shipping/on_site_service/digital; walk-in products → pos; walk-in services → queue; delivery → fulfilment+dispatch; on-site → jobs", "catalog", "EXTEND", P, "traits exist; no rules"),
        r("TX-11", "P1", "MD §4.3", "Trait group Stock: stock_tracked, perishable, weight_based, variant_based, serialised, made_to_order, ingredient_based → inventory (+batches/weights/serials); ingredient/made-to-order → recipes → procurement", "catalog", "EXTEND", P,
          "stock_tracked, serialised, ingredient_based missing"),
        r("TX-12", "P1", "MD §4.3", "Trait group People: provider_based, field_team, shift_staff → workforce, dispatch, attendance", "catalog", "EXTEND", P, "shift_staff missing"),
        r("TX-13", "P1", "MD §4.3", "Trait group Regulated: gst_registered, composition_scheme, food_licensed, health_regulated, finance_regulated, minors_involved → invoice mode, compliance, AI guardrails, guardian contacts, no marketing to minors", "catalog", "NEW", S, "none of these traits exist"),
        r("TX-14", "P1", "MD §4.3", "Trait group Presentation: portfolio_led, digital_only, nonprofit → portfolio sections; no address on site; donations", "catalog", "EXTEND", P, "digital_only missing"),
        r("TX-15", "P1", "MD §4.3", "Traits start from subcategory default, confirmed by ≤2 onboarding questions, editable later in Settings", "catalog", "NEW", S, "no stored traits, no settings editor"),
        r("TX-16", "P1", "MD §4.3 · §22", "Org shape: solo/team/multi_location/franchise_brand/franchise_outlet/enterprise — decides role templates and plan tier, not modules", "catalog", "NEW", S, "no org_shape"),
        r("TX-17", "P1", "MD §4.4", "businesses gains category_key, subcategory_key, org_shape; business_traits(business_id, trait_key, source default|owner|ai_suggested_confirmed)", "catalog", "NEW", S, "category in characteristics jsonb only", db="✗"),
        r("TX-18", "P1", "MD §4.4", "One versioned registry (taxonomy.py) owns taxonomy, synonyms, trait defaults, trait→module rules; frontend reads one endpoint; nothing hard-coded twice", "catalog", "EXTEND", P,
          "registry + endpoint exist; trait→module rules absent; marketplace groups 26 categories separately", svc="✓ /v1/taxonomy"),
        r("TX-19", "P1", "MD §4.4 · §27 · §24 #2", "Recommendation rules: pure function traits → Core/Recommended/Optional; every subcategory fixture asserts its module set", "catalog", "NEW", S, "no deterministic rules/fixtures", test="✗"),
        r("TX-20", "P1", "MD §22", "Operating model rows mapped to traits/org shape (23 rows, see section O)", "catalog", "NEW", S, "see OM-*"),
    ],
)

packs = Section(
    "D. Capability packs (MD §5; PDF §4) — presentation and packaging only; entitlements stay per module key",
    "A pack is COMPLETE when its presentation exists and every module it lists is COMPLETE.",
    [
        r("PK-00", "P1", "MD §5", "Pack registry used in onboarding/modules page to talk in outcomes; Storefront always on; business usually holds 2–4 packs", "catalog", "NEW", S, "no pack registry"),
        r("PK-01", "P1", "MD §5", "Storefront (all): website, marketplace listing, customer-relationships, reviews, messaging, insights, compliance", "pack", "EXTEND", P, "website/marketplace/CRM exist; reviews/messaging/insights/compliance absent"),
        r("PK-02", "P1", "MD §5", "Commerce: offerings-catalog, orders, payments, inventory, fulfilment, invoicing, pos, ledger, loyalty", "pack", "EXTEND", P, "first five exist; invoicing/pos/ledger/loyalty absent"),
        r("PK-03", "P2", "MD §5", "Food service: Commerce + table bookings, kitchen display, recipes, dine-in QR ordering, procurement", "pack", "NEW", S, "table booking mode exists; rest absent"),
        r("PK-04", "P2", "MD §5", "Appointments: services, bookings, workforce, queue, memberships (packages)", "pack", "EXTEND", P, "bookings/workforce exist; queue/packages absent"),
        r("PK-05", "P2", "MD §5", "Stays & rentals: bookings (date range), payments (deposits), tasks, documents, handover checklists", "pack", "EXTEND", P, "date_range resources + deposits exist; tasks/documents/checklists absent"),
        r("PK-06", "P2", "MD §5", "Memberships: memberships, attendance, payments, bookings (classes)", "pack", "EXTEND", P, "memberships basic; attendance absent"),
        r("PK-07", "P5", "MD §5", "Learning: academics, attendance, memberships (fee plans), documents", "pack", "NEW", S, "absent"),
        r("PK-08", "P2", "MD §5", "Sales & quotes: leads, quotes, projects, documents, invoicing, ledger", "pack", "EXTEND", P, "leads/quotes/projects exist"),
        r("PK-09", "P5", "MD §5", "Field service: jobs, dispatch, inventory (van stock), memberships (AMC), quotes", "pack", "NEW", S, "absent"),
        r("PK-10", "P2", "MD §5", "Delivery & dispatch: fulfilment, dispatch", "pack", "EXTEND", P, "fulfilment exists; dispatch absent"),
        r("PK-11", "P4", "MD §5", "Trade & supply: quotes (RFQ), price lists, invoicing (B2B, e-invoice, e-way bill), ledger, procurement, recipes, trade-network", "pack", "NEW", S, "quotes only"),
        r("PK-12", "P2", "MD §5", "Health front desk: bookings (provider/department), queue, workforce, documents (non-clinical forms), payments", "pack", "EXTEND", P, "bookings/workforce exist"),
        r("PK-13", "P3", "MD §5", "Growth: marketing, loyalty", "pack", "NEW", S, "absent"),
        r("PK-14", "P5", "MD §5", "Community & giving: memberships (dues), donations, bookings (hall), workforce (volunteers)", "pack", "NEW", S, "absent"),
        r("PK-15", "P4", "MD §5", "Back office: expenses, ledger, compliance, documents, connectors, payroll (FUTURE)", "pack", "NEW", S, "absent"),
    ],
)

surfaces = Section(
    "E. Surfaces and role workspaces (MD §7; PDF §5)",
    "A role is permissions + scope + default surface.",
    [
        r("SF-01", "P0", "MD §7.1", "Workspace (desktop/tablet web) for owner, manager, office roles", "core-workspace", "EXISTING", P,
          "apps/workspace exists; needs 12-area nav and role homes (FD-08/09)", ws="◐"),
        r("SF-02", "P2", "MD §7.1 · §13.3", "Crew app /crew: phone PWA for delivery, technician, housekeeping, provider on the move", "crew", "NEW", S, "absent"),
        r("SF-03", "P1", "MD §7.1 · §14", "POS: tablet/desktop full-screen for cashier", "pos", "NEW", S, "absent"),
        r("SF-04", "P2", "MD §7.1", "Kitchen display for kitchen stations", "kitchen", "NEW", S, "absent"),
        r("SF-05", "P0", "MD §7.1", "My Activity for customers", "platform", "EXISTING", P, "/activity exists (orders/bookings); see FD-02", cust="◐"),
        r("SF-06", "P5", "MD §7.1 · §20.3", "Guardian & student portal (phone web)", "academics", "NEW", S, "absent"),
        r("SF-07", "P4", "MD §7.1 · §16.5", "Supplier view: ChitBridge mailbox or magic-link PO page for off-network suppliers", "procurement", "NEW", S, "absent"),
        r("SF-08", "P6", "MD §7.1", "Brand HQ for franchise brand owners", "franchise", "FUTURE", F, "FUTURE by source"),
        r("RL-01", "P1", "MD §7.2", "Role template Owner: everything, approvals, billing, AI limits · business scope · Workspace", "team", "EXISTING", P, "primary_owner role holds all permissions; home is not 'Needs you now · Today · Your business'", perm="✓", ws="◐"),
        r("RL-02", "P1", "MD §7.2", "Manager: operations, approvals up to a limit, staff rota · location scope · Workspace", "team", "EXTEND", P, "manager role + location_scope array; no approval limits", perm="◐"),
        r("RL-03", "P2", "MD §7.2", "Front desk: bookings, queue, check-ins, customers, collect payments · location · Workspace", "team", "NEW", S, "tmpl_booking_coordinator is closest; no template"),
        r("RL-04", "P2", "MD §7.2", "Provider (doctor, stylist, trainer): own schedule/appointments/notes · assignment · Workspace or crew", "team", "NEW", S, "no assignment scope"),
        r("RL-05", "P1", "MD §7.2", "Cashier: POS, orders, payments, returns under a limit, cash shift · location · POS", "team", "EXTEND", P, "tmpl_cashier exists (orders/payments read); no POS/limits"),
        r("RL-06", "P2", "MD §7.2", "Kitchen: tickets for their station, no prices or phone numbers · location · KDS", "team", "NEW", S, "absent"),
        r("RL-07", "P1", "MD §7.2", "Store keeper: stock, goods receipt, counts, transfers, draft requisitions · location · Workspace", "team", "EXTEND", P, "tmpl_inventory_manager partial"),
        r("RL-08", "P2", "MD §7.2", "Dispatcher: dispatch board, assign crew, reassign failed jobs · location · Workspace", "team", "NEW", S, "absent"),
        r("RL-09", "P2", "MD §7.2", "Delivery partner: assigned deliveries; phone only while job active · assignment · Crew", "team", "NEW", S, "absent"),
        r("RL-10", "P5", "MD §7.2", "Technician: assigned job cards, parts, photos, asset service history · assignment · Crew", "team", "NEW", S, "absent"),
        r("RL-11", "P2", "MD §7.2", "Housekeeping: assigned room/area tasks · assignment · Crew", "team", "NEW", S, "absent"),
        r("RL-12", "P2", "MD §7.2", "Sales executive: assigned leads, quotes, site visits · assignment · Workspace or crew", "team", "NEW", S, "tmpl_lead_handler is business-scoped"),
        r("RL-13", "P5", "MD §7.2", "Teacher: own batches: attendance, assessments, announcements · assignment", "team", "NEW", S, "absent"),
        r("RL-14", "P1", "MD §7.2", "Accountant: invoices, ledger, expenses, exports, connectors; no customer messaging · business · Workspace", "team", "NEW", S, "absent"),
        r("RL-15", "P3", "MD §7.2", "Marketer: campaigns and audiences as counts; no phone-number export · business · Workspace", "team", "NEW", S, "absent"),
        r("RL-16", "P1", "MD §7.3", "Owners clone a template into custom roles; cannot exceed their own permissions", "team", "EXTEND", P, "templates + grants/denials + delegation ceiling exist; no clone UI", perm="✓ delegation ceiling", test="✓ test_authorization_engine"),
        r("RL-17", "P2", "MD §7.3 · §24 #11", "Assignment scope RLS arm assigned_member_id = current_member_id() on dispatch jobs, job cards, tasks, bookings, leads", "platform", "NEW", S, "absent", perm="✗"),
        r("RL-18", "P2", "MD §7.3", "test_actor_matrix.py extended with one row per role × record type before any crew surface ships", "platform", "EXTEND", P, "test_actor_matrix exists for current roles", test="◐"),
        r("RL-19", "P0", "MD §7.3", "One person holds roles in several businesses; context switching handles it", "platform", "EXISTING", C, "context switching shipped", test="✓ test_context_switching"),
        r("RL-20", "P3", "MD §7.3 · §8", "AI employees receive a role from §7.2 and never get Owner", "ai-employees", "NEW", S, "absent"),
    ],
)

primitives = Section(
    "F. Architecture primitives (MD §24; PDF §20)",
    "Built once, before the modules that lean on them. Every new table is business_id-scoped with RLS and tested in RLS-enforcing and bypass modes.",
    [
        r("PM-01", "P1", "MD §24 #1", "Taxonomy registry: versioned categories, subcategories, synonyms, trait defaults", "catalog", "EXTEND", P, "see TX-*", svc="✓"),
        r("PM-02", "P1", "MD §24 #2", "Recommendation rules: pure function traits → Core/Recommended/Optional, fixture-tested", "catalog", "NEW", S, "see TX-19"),
        r("PM-03", "P1", "MD §24 #3", "Domain events: named events written to the existing outbox", "events", "EXISTING", P,
          "outbox + catalogue checked at publish + subscriber registry; module events for new modules to be added", db="✓ platform_outbox_events", svc="✓", test="✓"),
        r("PM-04", "P1", "MD §24 #4", "Automation ladders: one generic engine for timed step sequences tied to an entity with idempotency keys — no per-module crons", "automation", "NEW", S,
          "scheduled_jobs + async_jobs exist; no ladder engine", db="◐ platform_scheduled_jobs"),
        r("PM-05", "P1", "MD §24 #5", "Number series: gapless, row-locked series per GSTIN × FY × register; offline blocks", "invoicing", "NEW", S, "order/quote numbers are per-module counters"),
        r("PM-06", "P1", "MD §24 #6", "Money: integer paise + currency code everywhere, matching ChitBridge stamped money", "platform", "EXTEND", P,
          "existing money columns are NUMERIC(12,2) decimal — exact but not integer paise"),
        r("PM-07", "P1", "MD §24 #7", "Document renderer: PDFs (invoice, quote, certificate, report card) from structured data, stored with a hash", "documents", "EXTEND", P,
          "quote_document renders print-ready HTML (no stored hash, no PDF)"),
        r("PM-08", "P1", "MD §24 #8 · §25", "Consent store: consent(customer, purpose, channel, source, granted_at, withdrawn_at) for DPDP + WhatsApp marketing", "customer-relationships", "NEW", S, "absent"),
        r("PM-09", "P1", "MD §24 #9", "Usage meters per business per resource (WhatsApp msgs, voice minutes, Maps calls, model tokens) with caps and alerts", "platform", "EXTEND", P, "generation_provider_usage for image/text generation only"),
        r("PM-10", "P2", "MD §24 #10", "Stage engine: configurable stage sets with guarded transitions shared by orders, jobs, leads, projects", "platform", "NEW", S, "each module hard-codes statuses"),
        r("PM-11", "P2", "MD §24 #11", "Assignment scope: RLS arm on assigned records + actor-matrix rows", "platform", "NEW", S, "see RL-17"),
        r("PM-12", "P1", "MD §24 #12", "Offline sync: client UUIDs, idempotent mutation endpoints, queued replays, conflict rules", "platform", "EXTEND", P, "idempotency_records + idempotency keys on orders/bookings; no client queue"),
        r("PM-13", "P2", "MD §24 #13", "Realtime + location: signed realtime channels; location_ping partitioned by day with TTL job", "dispatch", "NEW", S, "absent"),
        r("PM-14", "P3", "MD §24 #14", "AI employee runtime: actor type, tool registry, tiers, ai_action audit, kill switch", "ai-employees", "NEW", S, "absent"),
        r("PM-15", "P4", "MD §24 #15", "Connector hub: connector, sync_run, sync_mapping, secrets vault, agent pairing", "connectors", "NEW", S, "absent"),
        r("PM-16", "P2", "MD §24", "customer_asset (vehicle, pet, device, AC unit, policy, installed machine) shared by jobs, garages, vets, AMCs, advisers", "customer-relationships", "NEW", S, "absent"),
        r("PM-17", "X", "MD §24.2", "No module calls another module's automations directly; everything reacts to events", "events", "EXISTING", P, "subscriber registry pattern exists"),
        r("PM-18", "X", "MD §24.3", "Every migration has a unique timestamp prefix; CI fails on duplicates", "platform", "EXTEND", P, "prefixes unique today; no CI check"),
        r("PM-19", "X", "MD §24.3", "Every new table ships with its RLS policy, a cross-business isolation test and an actor-matrix row; no policy widened, no assertion weakened", "platform", "EXISTING", P, "rule followed for existing tables; enforced per packet"),
    ],
)

SECTIONS = [founder, principles, classification, packs, surfaces, primitives]
