"""Founder refinements (authority 1), added to Documentations/ on 2026-09-28/29:
`# FOUNDER REFINEMENT — INVENTORY / BOOKINGS / MEMBERSHIPS / PAYMENTS.txt`,
`B2B.txt` and `# FOUNDER REFINEMENT — ORDERS & CUSTOMER TRANSACTIONS.txt`. They
refine the MD/PDF scope of those modules; statuses here are the baseline when
they arrived (after P1-10A; Orders after P1-10D1 was committed) and move
through progress.py."""

from __future__ import annotations

from tools.ledger.model import Section, r

S = "NOT_STARTED"
P = "PARTIAL"
C = "COMPLETE"
A = "ACTIVATION_REQUIRED"

_INV_T = "✓ test_stock_depth + browser p1_10a_stock, p1_10a_counter_serials"
_OR_CHK = "✓ test_checkout_flow + test_orders_kernel + browser p1_03_kinds, p1_04_invoicing"
_OR_WA = "✓ test_journeys (fixture WhatsApp) + browser p1_08_journeys"

refinements = Section(
    "A2. Founder refinements — Inventory, Bookings, Memberships, Payments, B2B, Orders & Customer Transactions (2026-09-28/29)",
    "Founder documents that sharpen how each module must behave; each ends with a browser acceptance list. "
    "They rank with the founder prompt, above the PDF and the MD.",
    [
        # ---------------------------------------------------------------- inventory
        r("FR-IN-01", "P1", "FR-Inventory §1, §26", "One stock truth: POS, website, WhatsApp and bills move the same stock through one service; no channel stock copies", "inventory", "EXTEND", C,
          "[P1-10A] every path (counter, Workspace bill, online/WhatsApp order, count, cut, wastage) is a movement on the one record under its lock", test=_INV_T),
        r("FR-IN-02", "P1", "FR-Inventory §2", "Stock modes composed from real characteristics: simple, weight, yield/transformation, variant, batch/expiry (FEFO), serialised", "inventory", "EXTEND", C,
          "[P1-10A] modes from traits + §21 hints + configuration; FEFO on every sale path; serial per unit; yields and cutting runs", test=_INV_T),
        r("FR-IN-03", "P2", "FR-Inventory §2, §19", "Multi-location transfers: requested → approved where required → in transit → received; transit stock not free at either end", "inventory", "NEW", S,
          "per-location stock exists; transfers not built (IN-07)"),
        r("FR-IN-04", "P5", "FR-Inventory §2, §17", "Van / mobile stock: central → van; technician consumes parts against a job; unused parts returned", "inventory", "NEW", S,
          "needs van locations and Jobs (P5)"),
        r("FR-IN-05", "P4", "FR-Inventory §2, §10", "Ingredient/material consumption through Recipe/BOM when a finished item sells (shawarma, restaurant, manufacturer)", "recipes", "NEW", S,
          "Recipes & BOM is P4"),
        r("FR-IN-06", "P1", "FR-Inventory §4", "Receive stock: simple (qty + cost), batch (batch, expiry), serial (IMEI list), weight (kg + cost/kg); stock rises only on actual receipt", "inventory", "EXTEND", P,
          "[P1-10A] all four receive paths with total cost and buying units; cost-per-kg / per-unit entry not offered yet", test=_INV_T),
        r("FR-IN-07", "P1", "FR-Inventory §5", "Reserve on confirmed online/WhatsApp order, release on cancel, deduct on fulfil; returns restore the same serial and batch", "inventory", "EXTEND", C,
          "[P1-10A] reservations (First Launch + P1-08) with FEFO on deduction; returns and cancellations go back to the original batch and serial", test=_INV_T),
        r("FR-IN-08", "P1", "FR-Inventory §6", "Stock counts: expected/counted/variance with approval; by category/aisle for supermarkets; per location", "inventory", "EXTEND", P,
          "[P1-10A] blind counts, approval, applied against current stock, per location; category scope exists in the API but the Workspace start form offers no category picker yet", test=_INV_T),
        r("FR-IN-09", "P1", "FR-Inventory §7", "Wastage/write-off with reasons; prominent for food/fresh, not the main screen for electronics", "inventory", "EXTEND", C,
          "[P1-10A] reasons ordered per lens; wastage leads only on fresh/food views", test=_INV_T),
        r("FR-IN-10", "P1", "FR-Inventory §8, §9", "Reorder: minimum, target, safety stock → suggested replenish quantity as an input to Procurement (not a second purchasing system)", "inventory", "EXTEND", P,
          "[P1-10A] min and fill-up-to with suggested quantity; safety stock and the Procurement hand-off arrive with Buying (P4)", test=_INV_T),
        r("FR-IN-11", "P1", "FR-Inventory §3; B2B §4", "Available-to-promise excludes reserved and expired/unusable stock; confirmed inbound shown where Procurement exists", "inventory", "EXTEND", P,
          "[P1-10A] free = on hand − reserved; expired batches flagged and sold last; inbound needs Procurement (P4)", test=_INV_T),
        r("FR-IN-12", "P1", "FR-Inventory §11–§18, §21", "Inventory home adapts by trait/configuration: kirana, supermarket, meat, restaurant, pharmacy, fashion, electronics, field service, industrial", "inventory", "EXTEND", P,
          "[P1-10A] counter-by-weight, batches, serials, size grid, ingredients and reorder homes; restaurant recipe consumption (P4), field van (P5), industrial lots/raw-material homes (P4) not yet", test=_INV_T),
        r("FR-IN-13", "P2", "FR-Inventory §22", "Role views: store keeper (receive/count/transfer), cashier (sale-time stock, serial capture), kitchen (ingredients), technician (own van/job parts), picker (order items)", "inventory", "EXTEND", P,
          "[P1-10A] store keeper and cashier done; kitchen, technician and picker surfaces arrive with Kitchen (P2), Jobs (P5), Dispatch (P2)"),
        r("FR-IN-14", "P1", "FR-Inventory §23", "Inventory automations: low stock, expiring stock, count variance awaiting approval, transfer awaiting receipt, reorder suggestion", "inventory", "EXTEND", P,
          "[P1-10A] low-stock and expiry ladders; count-awaiting-approval notice, transfers and reorder suggestion not yet", auto="◐"),
        r("FR-IN-15", "P1", "FR-Inventory §24", "Inventory insights only from real data: on hand, value, low, near-expiry, wastage, count variance, movement, yield variance", "insights", "EXTEND", P,
          "[P1-10A] value, low, expiring, wastage and yield accuracy shown on the stock views; no Insights page yet (IS-01)"),
        r("FR-IN-16", "P1", "FR-Inventory §27", "Browser acceptance: 14 inventory scenarios (small shop, online reserve/release, kirana count, meat, restaurant recipe, pharmacy, fashion sale, electronics return, transfer, van, reorder, RLS, 390 px, regression)", "inventory", "EXTEND", P,
          "[P1-10A] meat cut + wastage, pharmacy expiry + write-off, fashion grid, electronics IMEI at the counter + lookup, count approval, 390 px; small-shop POS 24→22, online reserve/release, fashion variant sale, electronics return in the browser, transfer, van, restaurant and reorder→procurement not yet"),
        # ---------------------------------------------------------------- bookings
        r("FR-BK-01", "P2", "FR-Bookings §1", "One booking record from every channel (website, Marketplace, WhatsApp, phone/AI, front desk, Workspace) with the channel stored", "bookings", "EXTEND", P,
          "website, WhatsApp (P1-08) and Workspace create the same booking; phone/AI (P3) and front-desk surface (P2) not yet"),
        r("FR-BK-02", "P2", "FR-Bookings §2–§3", "Real availability from hours, provider/resource schedule, duration, buffers, bookings, blocks, capacity; re-checked with a slot lock at confirm", "bookings", "EXTEND", P,
          "availability engine + exclusive-resource constraint exist; buffers, horizon/notice rules and a commit-time slot hold per mode not complete"),
        r("FR-BK-03", "P2", "FR-Bookings §4–§14, §28", "Mode-specific flows and settings: appointment (service→provider/any→date→slot), table (date→time→party), stay (date range→room type), class (capacity/waitlist), rental (asset→range), site visit (→assigned salesperson), event date", "bookings", "EXTEND", S,
          "the website booking page is one generic start/end form for everyone"),
        r("FR-BK-04", "P2", "FR-Bookings §15–§17", "Recurring bookings (edit one / future), waitlist with customer acceptance, temporary holds that release when unpaid", "bookings", "NEW", S, "absent"),
        r("FR-BK-05", "P2", "FR-Bookings §18–§21", "Deposit/full payment via Payments; reschedule releases old slot and keeps history; cancellation by policy frees slot and triggers waitlist; arrival/no-show states", "bookings", "EXTEND", P,
          "deposits, cancel window and reschedule exist; waitlist reaction and mode-specific states not"),
        r("FR-BK-06", "P2", "FR-Bookings §24–§27", "Front desk calendar (today, next available, arrivals, no-shows), provider 'my schedule', owner utilisation; reminders; My Activity upcoming/past with reschedule/cancel/pay balance", "bookings", "EXTEND", P,
          "[P1-10B] customer account shows upcoming and past bookings with the manage link; front-desk and provider surfaces (P2)"),
        r("FR-BK-07", "P2", "FR-Bookings §30", "Browser acceptance: 15 booking scenarios incl. two simultaneous customers → exactly one succeeds", "bookings", "EXTEND", S, "not yet"),
        # ---------------------------------------------------------------- memberships
        r("FR-MB-01", "P2", "FR-Memberships §1–§3", "One recurring-relationship engine with plan kinds; per-kind language (Membership, Subscription, Fees/Enrolment, Service plan, Dues); periods never overwritten; deterministic states", "memberships", "EXTEND", S,
          "plans + enrolments with fixed statuses; no plan kinds, periods or per-kind language"),
        r("FR-MB-02", "P2", "FR-Memberships §4–§5", "Lifecycle recalculated on every event and by a daily business-timezone job; owner sees active/expiring/due/pending/grace/expired/paused; ladder stops after renewal", "memberships", "NEW", S, "absent"),
        r("FR-MB-03", "P2", "FR-Memberships §6–§8", "Gym: members board, QR check-in eligibility green/amber/red, freeze extends end by exactly the frozen days with history; session packs track remaining uses as the truth Bookings asks", "memberships", "NEW", S, "absent"),
        r("FR-MB-04", "P2", "FR-Memberships §9–§15", "Recurring delivery subscriptions: items, quantity, days, meal slots, window, address, prepaid/postpaid; cutoff generates tomorrow's orders; skip, pause, one-day quantity override, change future; any suitable product", "memberships", "NEW", S, "absent"),
        r("FR-MB-05", "P2", "FR-Memberships §16–§19", "Fee plans with instalments (paid/outstanding/next due, guardian payer, no auto-removal), AMC contracts with visits via Jobs, club dues with good standing", "memberships", "NEW", S, "absent"),
        r("FR-MB-06", "P2", "FR-Memberships §20–§21", "Autopay renews exactly once; failure follows retry → grace → expiry; early renewal queues the next period", "memberships", "NEW", S, "autopay needs Cashfree (activation)"),
        r("FR-MB-07", "P2", "FR-Memberships §22–§25", "Owner homes per kind (gym, milk/food, coaching, AMC, club); customer 'My …' per kind; WhatsApp renew/skip/pause buttons on the same service; Needs you now summaries", "memberships", "NEW", S, "absent"),
        r("FR-MB-08", "P2", "FR-Memberships §28", "Browser acceptance: gym renewal, freeze, session pack, milk skip/override/pause, tiffin counts, postpaid bill, coaching instalments, AMC, club, failure/grace, early renewal, RLS, 390 px", "memberships", "NEW", S, "not yet"),
        # ---------------------------------------------------------------- payments
        r("FR-PY-01", "P1", "FR-Payments §2–§4", "Payment states separate from the transaction (unpaid, pending, paid, failed, part-paid, refunded, part-refunded, expired); retry creates a new attempt, never a new order; pending checks the provider before another attempt", "payments", "EXTEND", P,
          "payment_attempts with statuses and webhook receipts exist; retry/pending-recheck flow for customers not built; provider is Cashfree (activation)"),
        r("FR-PY-02", "P1", "FR-Payments §5, §10", "Business chooses full / advance / % advance / deposit / pay later; total, paid and balance always shown; balance collectable later by link, counter, cash, UPI", "payments", "EXTEND", P,
          "booking deposits and counter split tender exist; order advances and a general balance view not"),
        r("FR-PY-03", "P1", "FR-Payments §7", "Secure payment link tied to the real order/booking/membership/invoice/balance for WhatsApp; webhook marks the same record paid", "payments", "EXTEND", S,
          "khata statement carries the business's own UPI link; provider payment links need Cashfree (PY-02)"),
        r("FR-PY-04", "P1", "FR-Payments §9, §12, §14", "Refunds linked to a prior payment (full/partial) keeping history; receipts through Invoicing; owner sees paid today, pending, failed, balances, refunds — verified payments only", "payments", "EXTEND", P,
          "refund records and invoice payments exist; owner payment overview incomplete"),
        # ---------------------------------------------------------------- orders & customer transactions
        r("FR-OR-01", "P1", "FR-Orders §channels", "Customer business accepted on every appropriate channel: website, Marketplace, WhatsApp, counter/POS, human phone order, AI phone order (where enabled), QR/table, reorder, governed external billing/connectors", "orders", "EXTEND", P,
          "website checkout, Marketplace (card → the business's own site), WhatsApp journeys, the counter and reorder exist; a staff phone order has only the raw API (FR-OR-13); AI phone (P3), QR/table (P2) and connectors (P4) not built"),
        r("FR-OR-02", "P1", "FR-Orders §routing", "Not every customer action is an Order: product/food → Orders; appointment/stay → Bookings; plan → Memberships; bill → Payments/Invoice/Ledger; RFQ → Quotes/B2B; site visit → Lead + Booking; donation → Donations; repair → Jobs/Bookings", "orders", "EXTEND", P,
          "checkout refuses booked and enquired kinds (kind.flow); the site's actions route to Book, See plans, Get a quote, site visit and pay links (P1-10C, P1-10D1); joining a plan is still an enquiry (Memberships P2), a site visit is a lead with a date (slots P2), gifts to a cause still ride the order path until Donations (P5), repair work waits for Jobs (P5)",
          test="✓ test_offering_kinds + test_module_aware_site"),
        r("FR-OR-03", "P1", "FR-Orders §one truth", "Every surface uses the same Orders service; no website_orders / whatsapp_orders / phone_orders / pos_orders copies; channel stored as provenance only", "orders", "EXTEND", C,
          "one orders_orders table with channel (web, whatsapp, pos, phone, workspace, marketplace); website and WhatsApp both place through CheckoutService.place_for_contact; counter sales are bills from the one invoicing engine and the one stock ledger, not an order copy",
          db="✓ orders_orders.channel", svc="✓ place_for_contact", test=_OR_WA + "; test_checkout_flow"),
        r("FR-OR-04", "P1", "FR-Orders §website checkout", "Website checkout: catalogue/menu → options/variant/weight/modifiers → cart → fulfilment → address → configured charges → payment choice → server price/stock/tax validation → confirmation → payment → order confirmation → My Activity/tracking", "orders", "EXTEND", P,
          "every step exists for pickup and local delivery with COD (options, packs, cuts and add-ons priced by the server; zone delivery charge; reservation; engine-priced invoice; confirmation with tracking and My Activity); dine-in and shipping fulfilment, charges other than the zone delivery charge, and online payment (Cashfree, FR-OR-08) are missing",
          web="◐ /{slug}/checkout", cust="✓ /track + /activity", test=_OR_CHK + ", p1_10b_identity"),
        r("FR-OR-05", "P1", "FR-Orders §website checkout", "Cart is not yet an Order: nothing is committed until the customer confirms", "orders", "EXTEND", C,
          "the website cart lives in the browser and the WhatsApp cart in the journey session; the order (and its reservation) is created only at Place order / the confirm button, once per idempotency key",
          test=_OR_CHK + "; test_journeys"),
        r("FR-OR-06", "P1", "FR-Orders §website checkout", "Server is authoritative for price, tax, discount validity, stock, availability, delivery charge and commercial total", "orders", "EXTEND", P,
          "price and option prices from the catalogue (a sent unit_price is ignored), tax from the invoicing engine, stock reserved at placement, delivery charge from the matched zone; availability windows (opening hours, cutoff, lead time) are not checked at checkout and there are no customer discount codes yet to validate",
          svc="◐", test=_OR_CHK),
        r("FR-OR-07", "P1", "FR-Orders §owner settings", "Owner configures only the order behaviour that applies: channels, pickup, delivery, dine-in, shipping, COD, online payment, minimum order, delivery area/charge, free-delivery threshold, preorder rules, cutoff, preparation lead time, cancellation, return/exchange, packing charge, GST, auto-accept vs review", "orders", "EXTEND", P,
          "pickup, delivery zones with charges, COD on/off with a first-order cap, GST treatment and readiness-driven channels exist; minimum order, free-delivery threshold, preorder rules, cutoff, lead time, cancellation/return policy, packing charge, auto-accept and dine-in are absent, shipping needs an aggregator (FU-02), and settings are not filtered to what the business uses"),
        r("FR-OR-08", "P1", "FR-Orders §payment", "Website payment through the business's own merchant path; customer → business money kept apart from business → LOCAH platform billing", "payments", "EXTEND", A,
          "the separation is structural (payments_* for merchant money, commercial_entitlements for the platform; no merchant money in platform tables); online payment at checkout needs a live merchant connection through Cashfree (PY-10) — COD, recorded and direct-UPI collection work without it"),
        r("FR-OR-09", "P1", "FR-Orders §payment", "Payment status separate from order status; Order (commitment) and Invoice (tax document) are distinct records from one shared Invoicing", "orders", "EXTEND", C,
          "orders carry status and payment_status independently (partially_paid since P1-10D1); invoices are issued from an order by the one billing engine (automatically on accept/complete or on demand), never a website-only receipt",
          test="✓ test_invoicing_gst + test_payment_collect + browser p1_04_invoicing"),
        r("FR-OR-10", "P1", "FR-Orders §POS", "Counter workflow: scan/search → cart → quantity/variant/serial/weight → tender → bill → stock movement → receipt; counter sales join the business's and the customer's history", "pos", "EXTEND", P,
          "the counter does the whole workflow (P1-05/06, serials and batches P1-10A); a counter bill for a named customer reaches their My Activity and khata, but bills do not yet write the owner's customer timeline (CR-02)",
          test="✓ test_pos + browser p1_05_pos, p1_10a_counter_serials"),
        r("FR-OR-11", "P1", "FR-Orders §WhatsApp", "WhatsApp is a channel: structured ordering catalogue → lines/options → cart → fulfilment → address → payment/COD → explicit confirmation → the same Orders service", "messaging", "EXTEND", A,
          "structured journey built on the same order service with the customer's button at confirm and re-pricing (MS-10, MS-18), fixture-verified; a live number needs Meta activation (OD-02)",
          test=_OR_WA),
        r("FR-OR-12", "P3", "FR-Orders §WhatsApp", "AI WhatsApp ordering (free text) builds the same cart and order; AI never invents price, stock, discount or delivery charge", "ai-employees", "NEW", S,
          "needs the AI employee runtime (MS-25)"),
        r("FR-OR-13", "P1", "FR-Orders §phone", "Human phone order: staff create the same Order with the current catalogue, stock, pricing, tax, delivery and payment rules", "orders", "EXTEND", P,
          "POST /orders (orders.create) prices from the catalogue and reserves stock with channel phone/workspace, but there is no Workspace screen to take an order on a call, and that path skips the fulfilment job, delivery charge and COD rules the checkout applies"),
        r("FR-OR-14", "P3", "FR-Orders §phone", "AI phone ordering where explicitly enabled: real catalogue, cart, required options, availability re-check, read-back with total, explicit confirmation, digital payment link, audited actor_type=ai_employee order; never card details by voice; complex/custom/negotiated/high-risk/low-confidence → human or WhatsApp confirmation", "ai-employees", "NEW", S,
          "AI Receptionist is P3; telephony needs OD-08/OD-09. SOURCE_CONFLICT SC-01 (MD §11.2 'Nothing else') resolved for the founder"),
        r("FR-OR-15", "P2", "FR-Orders §restaurant", "Restaurant/QSR: dine-in, table/QR, takeaway, pickup, delivery and Kitchen/KOT on the one order — no QR-specific order truth", "orders", "EXTEND", P,
          "takeaway/pickup and delivery run on the one order; dine-in/table/QR (OR-03) and kitchen tickets (KT-01..04) are not built"),
        r("FR-OR-16", "P1", "FR-Orders §pre-orders", "Pre-orders / scheduled orders (bakery, meat/fresh, home kitchen, festival, custom prepared): required date/time, cutoff, lead time; operational view of prepare now / today / tomorrow / future / overdue", "orders", "EXTEND", S,
          "orders have no requested date; OR-04 is packet P1-10D2"),
        r("FR-OR-17", "P1", "FR-Orders §partial availability", "Partial availability never silently changes the purchase: reduce quantity, remove, alternative, preorder/wait or talk to the business → recalculate → reconfirm", "orders", "EXTEND", P,
          "WhatsApp offers 'Make it N' or remove and asks again (MS-18); the website refuses a short cart with an error; alternatives and preorder/wait are not offered, and a business that finds a line short after accepting has no reconfirmation flow",
          test=_OR_WA),
        r("FR-OR-18", "P1", "FR-Orders §edits · MD §12.3", "Order edits revalidate price, stock, tax, delivery and payment difference and keep audit history", "orders", "EXTEND", S,
          "PATCH /orders changes only the internal reference and payment status; lines cannot be changed after placing"),
        r("FR-OR-19", "P1", "FR-Orders §cancellation", "Cancellation releases the reservation, reacts to preparation/dispatch, refunds through Payments and tells the customer", "orders", "EXTEND", P,
          "cancel releases the reservation, cancels the delivery job and writes My Activity; WhatsApp customers can cancel while pending (MS-16); a paid order's refund is a separate owner action, no cancellation message is sent, and there is no policy by preparation stage",
          test="✓ test_orders_kernel + test_fulfilment_kernel"),
        r("FR-OR-20", "P2", "FR-Orders §returns · MD §6.1", "Returns/exchanges link to the original transaction, keep the exact SKU/variant/serial/batch, update stock and refund or credit-note through the proper modules", "orders", "EXTEND", P,
          "counter returns do all of it (PS-05; serial and batch back since P1-10A); returns and exchanges of online/WhatsApp orders (OR-05) are not built",
          test="✓ test_pos + test_stock_depth"),
        r("FR-OR-21", "P1", "FR-Orders §reorder", "Reorder is a convenience: re-check current catalogue, price, stock, availability and delivery rule, show the new total and ask to confirm", "orders", "EXTEND", C,
          "website Order again refills the cart at today's price, names what is no longer sold and goes through the full checkout again (stock reserved, delivery charge recomputed); WhatsApp repeat re-prices and asks for the button; availability windows arrive with FR-OR-07",
          test="✓ test_customer_identity + test_journeys + browser p1_10b_identity"),
        r("FR-OR-22", "P1", "FR-Orders §workspace", "One combined Orders workspace across channels — no Website/WhatsApp/Phone/Marketplace tabs; channel is a filter and provenance", "orders", "EXTEND", P,
          "one list with the channel shown per order ('From'); channel is not yet a filter",
          ws="◐ Orders"),
        r("FR-OR-23", "P1", "FR-Orders §workspace · specialization rule", "Orders workflow adapts to the business: kirana picking/ready/delivery/pickup; meat new/cut-prep/weight exceptions/ready; QSR new/preparing/ready/pickup/delivery; restaurant dine-in/takeaway/delivery/KDS; bakery today/tomorrow/custom preorders; retail processing/shipping/returns — never one generic CRUD table", "orders", "EXTEND", S,
          "the Orders page is the same status table (Pending … Cancelled) for every business"),
        r("FR-OR-24", "X", "FR-Orders §domains", "Bookings, Memberships, Payments, Invoicing, Inventory, Kitchen, Fulfilment and Dispatch stay separate domains connected to Orders", "orders", "EXTEND", C,
          "separate services joined by service calls and events (invoicing_auto, fulfilment_cancellation, the stock ledger, payment_collect); Kitchen and Dispatch will join the same way when built"),
        r("FR-OR-25", "P4", "FR-Orders §B2B; B2B refinement", "B2B is its own experience: consumer Orders carry no RFQs, MOQs, credit terms, supplier chits or B2B price lists unless the business uses B2B; a committed B2B sale may reuse order primitives", "orders", "EXTEND", P,
          "consumer Orders carry none of these today; the B2B sales experience itself is FR-B2B-01..07 (P4)"),
        r("FR-OR-26", "P1", "FR-Orders §recommendation", "Which order features a business sees comes from category + owner-confirmed traits + operating model + enabled modules + readiness (shawarma Orders+POS+Kitchen+delivery/pickup; kirana POS+Inventory+Orders+WhatsApp+Khata; hotel Bookings-first; consultant Leads/Bookings/Quotes/Projects), not business-name branches", "orders", "EXTEND", P,
          "module recommendations come from traits for every subcategory (P1-01 fixture) and the site's actions from readiness (P1-10C); the features inside Orders (which settings, which board) are not yet chosen from these rules",
          test="✓ test_taxonomy_recommendations + test_module_aware_site"),
        r("FR-OR-27", "P1", "FR-Orders §acceptance", "Browser acceptance (P1 part): website retail checkout, WhatsApp ordering, POS sale, human phone order, meat weight/cut, bakery preorder, partial availability, reorder, cancel, multi-channel combined owner view, RLS, 390 px", "orders", "EXTEND", P,
          "website checkout (p1_03, p1_04), WhatsApp ordering (p1_08), POS sale (p1_05), meat by weight (p1_03, p1_10a) and reorder (p1_10b) exist; human phone order, bakery preorder, partial availability on the website, cancel and the combined owner view are not yet flows"),
        r("FR-OR-28", "P2", "FR-Orders §acceptance", "Browser acceptance (P2 part): restaurant table order with KDS; return/exchange of an order", "orders", "EXTEND", S, "not yet"),
        r("FR-OR-29", "P3", "FR-Orders §acceptance", "Browser acceptance (P3 part): AI phone order fixture (replayed, zero provider calls)", "ai-employees", "NEW", S, "not yet"),
        r("FR-OR-30", "P4", "FR-Orders §acceptance", "Browser acceptance (P4 part): shawarma sale + Kitchen ticket + ingredient stock consumed through the recipe", "recipes", "NEW", S, "needs Kitchen (P2) and Recipes (P4)"),
        # ---------------------------------------------------------------- B2B
        r("FR-B2B-01", "P4", "B2B §1, §10", "Supplier relationships (on or off LOCAH): item mapping, supplier code, unit, pack, MOQ, price and history, lead time, delivery days, terms, preferred/fallback, connection state", "procurement", "NEW", S, "absent"),
        r("FR-B2B-02", "P4", "B2B §2, §13", "Three purchase origins: standing/recurring (edit one occurrence, skip, pause, change future), ad-hoc, demand-driven", "procurement", "NEW", S, "absent"),
        r("FR-B2B-03", "P4", "B2B §3–§5, §9", "Demand & Supply planning: aggregate all buyer demand (orders, bookings, subscriptions, forecast, par) with drill-down; BOM/yield conversion; net = demand + safety − ATP − inbound; pack/MOQ rounding", "procurement", "NEW", S, "absent"),
        r("FR-B2B-04", "P4", "B2B §6–§7", "Suggested requisition → review/edit → approve & send; owner-set auto-approval limits only; supplier counter (qty/price/date) with diff → accept/counter/decline", "procurement", "NEW", S, "absent"),
        r("FR-B2B-05", "P4", "B2B §8, §11", "A PO received by a LOCAH supplier becomes their incoming B2B sales order; their planning repeats upstream; buyer and supplier records stay distinct (sales order ≠ requisition ≠ PO ≠ GRN ≠ bill)", "trade-network", "NEW", S,
          "needs ChitBridge dependency gate"),
        r("FR-B2B-06", "P4", "B2B §12", "Goods receipt with actual quantity/weight, batch, cost, shortage and quality issue → inventory up by actual, payable linked, dispute path", "procurement", "NEW", S,
          "the P1-10A receive function is the stock half of a GRN"),
        r("FR-B2B-07", "P4", "B2B acceptance", "Browser acceptance: 15 B2B scenarios (3-node chain, 100 buyers → 30 net, safety/inbound, standing order, counter, GRN, idempotent webhooks, off-network supplier, isolation, recursive upstream)", "procurement", "NEW", S, "not yet"),
    ],
)

SECTIONS = [refinements]
