/** Doc 12 §11.2 reserved platform path segments — cannot be Business slugs. */
export const RESERVED_SLUGS = new Set([
  'search',
  'auth',
  'activity',
  'api',
  'admin',
  'static',
  '_next',
  'health',
  'webhooks',
  'about',
  'terms',
  'privacy',
  'help',
  'support',
  'blog',
  'pricing',
  'marketplace',
  'app',
  'b',
  'public',
  'login',
  'marketplace',
  'sitemap.xml',
  'robots.txt',
])
